/**
 * @file
 * @brief Function prototypes for the emitter functions.
 * @note  DO NOT EDIT THIS FILE, your changes will be lost.
 *         Edit ./ir/be/arm/arm_spec.pl instead.
 *         created by: ./ir/be/scripts/generate_emitter.pl ./ir/be/arm/arm_spec.pl build/gen/ir/be/arm
 * @date  Wed Jul 10 12:01:46 2024
 */
#ifndef FIRM_BE_ARM_GEN_ARM_EMITTER_H
#define FIRM_BE_ARM_GEN_ARM_EMITTER_H

void arm_register_spec_emitters(void);
void arm_register_spec_binary_emitters(void);

#endif
