#ifndef _BOUNCE_
#define _BOUNCE_

// Generated by Oberon+ IDE (Mono) 0.9.106 on 2024-07-13T01:26:30

#include "OBX.Runtime.h"
#include "som.Random.h"
#include "Benchmark.h"

// Declaration of module Bounce

struct Bounce$Bounce$Class$;
struct Bounce$Bounce;
struct Bounce$Ball$Class$;
struct Bounce$Ball;
struct Bounce$Bounce {
    struct Bounce$Bounce$Class$* class$;
};

extern void Bounce$Bounce$init$(struct Bounce$Bounce*);
struct Bounce$Ball {
    struct Bounce$Ball$Class$* class$;
    int32_t x;
    int32_t y;
    int32_t xVel;
    int32_t yVel;
};

extern void Bounce$Ball$init$(struct Bounce$Ball*);
struct Bounce$Ball * Bounce$createBall();
uint8_t Bounce$Ball$bounce(void* this);
struct Bounce$Bounce * Bounce$create();
struct Benchmark$Result * Bounce$Bounce$benchmark(void* this);
uint8_t Bounce$Bounce$verifyResult(void* this, struct Benchmark$Result * result);
struct Bounce$Bounce$Class$ {
    struct Benchmark$Benchmark$Class$* super$;
    struct Benchmark$Result * (*benchmark)(void* this);
    uint8_t (*verifyResult)(void* this, struct Benchmark$Result * result);
    uint8_t (*innerBenchmarkLoop)(void* this, int32_t innerIterations);
};
extern struct Bounce$Bounce$Class$ Bounce$Bounce$class$;

struct Bounce$Ball$Class$ {
    struct Bounce$Ball$Class$* super$;
    uint8_t (*bounce)(void* this);
};
extern struct Bounce$Ball$Class$ Bounce$Ball$class$;

extern void Bounce$init$(void);
extern OBX$Cmd Bounce$cmd$(const char* name);
#endif
