// Generated by Oberon+ IDE (Mono) 0.9.106 on 2024-07-13T01:26:30

#include "NBody.h"

void NBody$Body$init$(struct NBody$Body* inst){
    inst->class$ = &NBody$Body$class$;
}
void NBody$NBodySystem$init$(struct NBody$NBodySystem* inst){
    inst->class$ = &NBody$NBodySystem$class$;
}
void NBody$NBody$init$(struct NBody$NBody* inst){
    inst->class$ = &NBody$NBody$class$;
}
struct NBody$NBody * NBody$create() {
    struct NBody$NBody * n;
    struct NBody$NBody * $t0;
    n = 0;
    $t0 = OBX$Alloc(sizeof(struct NBody$NBody));
    memset($t0,0,sizeof(struct NBody$NBody));
    n = $t0;
    NBody$NBody$init$($t0);
    return n;
}

struct Benchmark$Result * NBody$NBody$benchmark(void* this) {
    struct NBody$NBody* this$ = this;
    assert(0);
    return 0;
}

uint8_t NBody$NBody$verifyResult(void* this, struct Benchmark$Result * result) {
    struct NBody$NBody* this$ = this;
    assert(0);
    return 0;
}

uint8_t NBody$NBody$innerBenchmarkLoop(void* this, int32_t innerIterations) {
    struct NBody$NBody* this$ = this;
    struct NBody$NBodySystem * system;
    int32_t i;
    void* $t0;
    void (* $t1)(void*, double);
    uint8_t (* $t2)(void*, double, int32_t);
    void* $t3;
    double (* $t4)(void*);
    system = 0;
    i = 0;
    system = NBody$createSystem();
    i = 0;
    while(1) {
        if( (i <= (innerIterations - 1)) ) {
            ($t1 = ((struct NBody$NBodySystem *)($t0 = &(*system)))->class$->advance, $t1($t0, 1.0000000e-02));
            i = (i + 1);
        } else {
            break;
        }
    }
    return ($t2 = ((struct NBody$NBody *)($t0 = &(*this$)))->class$->verifyResult2, $t2($t0, ($t4 = ((struct NBody$NBodySystem *)($t3 = &(*system)))->class$->energy, $t4($t3)), innerIterations));
}

uint8_t NBody$NBody$verifyResult2(void* this, double result, int32_t innerIterations) {
    struct NBody$NBody* this$ = this;
    if( (innerIterations == 250000) ) {
        return ((fabs(result) - 1.6908598899093080e-01) < 5.0000000e-17);
    } 
    if( (innerIterations == 1) ) {
        return ((fabs(result) - 1.6907495402506745e-01) < 5.0000000e-17);
    } 
    Out$String((const struct OBX$Array$1){28,0,OBX$FromUtf("No verification result for ",28,0)});
    Out$Int(innerIterations, 0);
    Out$String((const struct OBX$Array$1){7,0,OBX$FromUtf(" found",7,0)});
    Out$Ln();
    Out$String((const struct OBX$Array$1){12,0,OBX$FromUtf("Result is: ",12,0)});
    Out$Real(result, 0);
    Out$Ln();
    return 0;
}

struct NBody$Body * NBody$createBody(double x, double y, double z, double vx, double vy, double vz, double mass) {
    struct NBody$Body * b;
    struct NBody$Body * $t0;
    b = 0;
    $t0 = OBX$Alloc(sizeof(struct NBody$Body));
    memset($t0,0,sizeof(struct NBody$Body));
    b = $t0;
    NBody$Body$init$($t0);
    (*b).x = x;
    (*b).y = y;
    (*b).z = z;
    (*b).vx = (vx * 3.6524000e+02);
    (*b).vy = (vy * 3.6524000e+02);
    (*b).vz = (vz * 3.6524000e+02);
    (*b).mass = (mass * 3.9478417604357432e+01);
    return b;
}

struct NBody$Body * NBody$jupiter() {
    return NBody$createBody(4.8414314424647209e+00, (-1.1603200440274284e+00), (-1.0362204447112311e-01), 1.6600766427440369e-03, 7.6990111841974043e-03, (-6.9046001697206302e-05), 9.5479193842432661e-04);
}

struct NBody$Body * NBody$saturn() {
    return NBody$createBody(8.3433667182445799e+00, 4.1247985641243048e+00, (-4.0352341711432138e-01), (-2.7674251072686241e-03), 4.9985280123491724e-03, 2.3041729757376393e-05, 2.8588598066613081e-04);
}

struct NBody$Body * NBody$uranus() {
    return NBody$createBody(1.2894369562139131e+01, (-1.5111151401698631e+01), (-2.2330757889265573e-01), 2.9646013756476162e-03, 2.3784717395948095e-03, (-2.9658956854023756e-05), 4.3662440433515630e-05);
}

struct NBody$Body * NBody$neptune() {
    return NBody$createBody(1.5379697114850917e+01, (-2.5919314609987964e+01), 1.7925877295037118e-01, 2.6806777249038932e-03, 1.6282417003824230e-03, (-9.5159225451971587e-05), 5.1513890204661145e-05);
}

struct NBody$Body * NBody$sun() {
    return NBody$createBody(0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.0000000e+00);
}

void NBody$Body$offsetMomentum(void* this, double px, double py, double pz) {
    struct NBody$Body* this$ = this;
    (*this$).vx = (0.0000000e+00 - (px / 3.9478417604357432e+01));
    (*this$).vy = (0.0000000e+00 - (py / 3.9478417604357432e+01));
    (*this$).vz = (0.0000000e+00 - (pz / 3.9478417604357432e+01));
}

struct NBody$NBodySystem * NBody$createSystem() {
    struct NBody$NBodySystem * s;
    int32_t i;
    double px;
    double py;
    double pz;
    struct NBody$NBodySystem * $t0;
    struct OBX$Array$1* $t1;
    struct OBX$Array$1* $t2;
    void* $t3;
    void (* $t4)(void*, double, double, double);
    s = 0;
    i = 0;
    px = 0;
    py = 0;
    pz = 0;
    $t0 = OBX$Alloc(sizeof(struct NBody$NBodySystem));
    memset($t0,0,sizeof(struct NBody$NBodySystem));
    s = $t0;
    NBody$NBodySystem$init$($t0);
    (((struct NBody$Body * *)((struct OBX$Array$1){5,1,(*s).bodies}).$a)[0]) = NBody$sun();
    (((struct NBody$Body * *)((struct OBX$Array$1){5,1,(*s).bodies}).$a)[1]) = NBody$jupiter();
    (((struct NBody$Body * *)((struct OBX$Array$1){5,1,(*s).bodies}).$a)[2]) = NBody$saturn();
    (((struct NBody$Body * *)((struct OBX$Array$1){5,1,(*s).bodies}).$a)[3]) = NBody$uranus();
    (((struct NBody$Body * *)((struct OBX$Array$1){5,1,(*s).bodies}).$a)[4]) = NBody$neptune();
    px = 0.0000000e+00;
    py = 0.0000000e+00;
    pz = 0.0000000e+00;
    i = 0;
    while(1) {
        if( (i <= (5 - 1)) ) {
            px = (px + ((*(((struct NBody$Body * *)((struct OBX$Array$1){5,1,(*s).bodies}).$a)[i])).vx * (*(((struct NBody$Body * *)((struct OBX$Array$1){5,1,(*s).bodies}).$a)[i])).mass));
            py = (py + ((*(((struct NBody$Body * *)((struct OBX$Array$1){5,1,(*s).bodies}).$a)[i])).vy * (*(((struct NBody$Body * *)((struct OBX$Array$1){5,1,(*s).bodies}).$a)[i])).mass));
            pz = (pz + ((*(((struct NBody$Body * *)((struct OBX$Array$1){5,1,(*s).bodies}).$a)[i])).vz * (*(((struct NBody$Body * *)((struct OBX$Array$1){5,1,(*s).bodies}).$a)[i])).mass));
            i = (i + 1);
        } else {
            break;
        }
    }
    ($t4 = ((struct NBody$Body *)($t3 = &(*(((struct NBody$Body * *)((struct OBX$Array$1){5,1,(*s).bodies}).$a)[0]))))->class$->offsetMomentum, $t4($t3, px, py, pz));
    return s;
}

void NBody$NBodySystem$advance(void* this, double dt) {
    struct NBody$NBodySystem* this$ = this;
    int32_t i;
    int32_t j;
    double dx;
    double dy;
    double dz;
    double dSquared;
    double distance;
    double mag;
    struct NBody$Body * iBody;
    struct NBody$Body * jBody;
    struct OBX$Array$1* $t0;
    i = 0;
    j = 0;
    dx = 0;
    dy = 0;
    dz = 0;
    dSquared = 0;
    distance = 0;
    mag = 0;
    iBody = 0;
    jBody = 0;
    i = 0;
    while(1) {
        if( (i <= (5 - 1)) ) {
            iBody = (((struct NBody$Body * *)((struct OBX$Array$1){5,1,(*this$).bodies}).$a)[i]);
            j = (i + 1);
            while(1) {
                if( (j <= (5 - 1)) ) {
                    jBody = (((struct NBody$Body * *)((struct OBX$Array$1){5,1,(*this$).bodies}).$a)[j]);
                    dx = ((*iBody).x - (*jBody).x);
                    dy = ((*iBody).y - (*jBody).y);
                    dz = ((*iBody).z - (*jBody).z);
                    dSquared = (((dx * dx) + (dy * dy)) + (dz * dz));
                    distance = MathL$sqrt(dSquared);
                    mag = (dt / (dSquared * distance));
                    (*iBody).vx = ((*iBody).vx - ((dx * (*jBody).mass) * mag));
                    (*iBody).vy = ((*iBody).vy - ((dy * (*jBody).mass) * mag));
                    (*iBody).vz = ((*iBody).vz - ((dz * (*jBody).mass) * mag));
                    (*jBody).vx = ((*jBody).vx + ((dx * (*iBody).mass) * mag));
                    (*jBody).vy = ((*jBody).vy + ((dy * (*iBody).mass) * mag));
                    (*jBody).vz = ((*jBody).vz + ((dz * (*iBody).mass) * mag));
                    j = (j + 1);
                } else {
                    break;
                }
            }
            i = (i + 1);
        } else {
            break;
        }
    }
    i = 0;
    while(1) {
        if( (i <= (5 - 1)) ) {
            iBody = (((struct NBody$Body * *)((struct OBX$Array$1){5,1,(*this$).bodies}).$a)[i]);
            (*iBody).x = ((*iBody).x + (dt * (*iBody).vx));
            (*iBody).y = ((*iBody).y + (dt * (*iBody).vy));
            (*iBody).z = ((*iBody).z + (dt * (*iBody).vz));
            i = (i + 1);
        } else {
            break;
        }
    }
}

double NBody$NBodySystem$energy(void* this) {
    struct NBody$NBodySystem* this$ = this;
    double dx;
    double dy;
    double dz;
    double distance;
    double e;
    struct NBody$Body * iBody;
    struct NBody$Body * jBody;
    int32_t i;
    int32_t j;
    struct OBX$Array$1* $t0;
    dx = 0;
    dy = 0;
    dz = 0;
    distance = 0;
    e = 0;
    iBody = 0;
    jBody = 0;
    i = 0;
    j = 0;
    e = 0.0000000e+00;
    i = 0;
    while(1) {
        if( (i <= (5 - 1)) ) {
            iBody = (((struct NBody$Body * *)((struct OBX$Array$1){5,1,(*this$).bodies}).$a)[i]);
            e = (e + ((5.0000000e-01 * (*iBody).mass) * ((((*iBody).vx * (*iBody).vx) + ((*iBody).vy * (*iBody).vy)) + ((*iBody).vz * (*iBody).vz))));
            j = (i + 1);
            while(1) {
                if( (j <= (5 - 1)) ) {
                    jBody = (((struct NBody$Body * *)((struct OBX$Array$1){5,1,(*this$).bodies}).$a)[j]);
                    dx = ((*iBody).x - (*jBody).x);
                    dy = ((*iBody).y - (*jBody).y);
                    dz = ((*iBody).z - (*jBody).z);
                    distance = MathL$sqrt((((dx * dx) + (dy * dy)) + (dz * dz)));
                    e = (e - (((*iBody).mass * (*jBody).mass) / distance));
                    j = (j + 1);
                } else {
                    break;
                }
            }
            i = (i + 1);
        } else {
            break;
        }
    }
    return e;
}

struct NBody$Body$Class$ NBody$Body$class$ = { 
    0,
    NBody$Body$offsetMomentum,
};

struct NBody$NBodySystem$Class$ NBody$NBodySystem$class$ = { 
    0,
    NBody$NBodySystem$advance,
    NBody$NBodySystem$energy,
};

struct NBody$NBody$Class$ NBody$NBody$class$ = { 
    &Benchmark$Benchmark$class$,
    NBody$NBody$benchmark,
    NBody$NBody$verifyResult,
    NBody$NBody$innerBenchmarkLoop,
    NBody$NBody$verifyResult2,
};

static int initDone$ = 0;
void NBody$init$(void) {
    if(initDone$) return; else initDone$ = 1;
    MathL$init$();
    Benchmark$init$();
    Out$init$();
}
OBX$Cmd NBody$cmd$(const char* name) {
    if( name == 0 ) return NBody$init$;
    return 0;
}
