// Generated by Oberon+ IDE (Mono) 0.9.106 on 2024-07-13T01:26:30

#include "Queens.h"

void Queens$Queens$init$(struct Queens$Queens* inst){
    inst->class$ = &Queens$Queens$class$;
}
struct Queens$Queens * Queens$create() {
    struct Queens$Queens * q;
    struct Queens$Queens * $t0;
    q = 0;
    $t0 = OBX$Alloc(sizeof(struct Queens$Queens));
    memset($t0,0,sizeof(struct Queens$Queens));
    q = $t0;
    Queens$Queens$init$($t0);
    return q;
}

struct Benchmark$Result * Queens$Queens$benchmark(void* this) {
    struct Queens$Queens* this$ = this;
    uint8_t result;
    int32_t i;
    struct Benchmark$BoolResult * res;
    void* $t0;
    uint8_t (* $t1)(void*);
    struct Benchmark$BoolResult * $t2;
    result = 0;
    i = 0;
    res = 0;
    result = 1;
    i = 0;
    while(1) {
        if( (i <= (10 - 1)) ) {
            result = (result && ($t1 = ((struct Queens$Queens *)($t0 = &(*this$)))->class$->queens, $t1($t0)));
            i = (i + 1);
        } else {
            break;
        }
    }
    $t2 = OBX$Alloc(sizeof(struct Benchmark$BoolResult));
    memset($t2,0,sizeof(struct Benchmark$BoolResult));
    res = $t2;
    Benchmark$BoolResult$init$($t2);
    (*res).res = result;
    return ((struct Benchmark$Result *)res);
}

uint8_t Queens$Queens$queens(void* this) {
    struct Queens$Queens* this$ = this;
    int32_t i;
    struct OBX$Array$1* $t0;
    void* $t1;
    uint8_t (* $t2)(void*, int32_t);
    i = 0;
    i = 0;
    while(1) {
        if( (i <= (8 - 1)) ) {
            (((uint8_t *)((struct OBX$Array$1){8,1,(*this$).freeRows}).$a)[i]) = 1;
            (((int32_t *)((struct OBX$Array$1){8,1,(*this$).queenRows}).$a)[i]) = (-1);
            i = (i + 1);
        } else {
            break;
        }
    }
    i = 0;
    while(1) {
        if( (i <= (16 - 1)) ) {
            (((uint8_t *)((struct OBX$Array$1){16,1,(*this$).freeMaxs}).$a)[i]) = 1;
            (((uint8_t *)((struct OBX$Array$1){16,1,(*this$).freeMins}).$a)[i]) = 1;
            i = (i + 1);
        } else {
            break;
        }
    }
    return ($t2 = ((struct Queens$Queens *)($t1 = &(*this$)))->class$->placeQueen, $t2($t1, 0));
}

uint8_t Queens$Queens$placeQueen(void* this, int32_t c) {
    struct Queens$Queens* this$ = this;
    int32_t r;
    void* $t0;
    uint8_t (* $t1)(void*, int32_t, int32_t);
    struct OBX$Array$1* $t2;
    void (* $t3)(void*, int32_t, int32_t, uint8_t);
    uint8_t (* $t4)(void*, int32_t);
    r = 0;
    r = 0;
    while(1) {
        if( (r <= (8 - 1)) ) {
            if( ($t1 = ((struct Queens$Queens *)($t0 = &(*this$)))->class$->getRowColumn, $t1($t0, r, c)) ) {
                (((int32_t *)((struct OBX$Array$1){8,1,(*this$).queenRows}).$a)[r]) = c;
                ($t3 = ((struct Queens$Queens *)($t0 = &(*this$)))->class$->setRowColumn, $t3($t0, r, c, 0));
                if( (c == 7) ) {
                    return 1;
                } 
                if( ($t4 = ((struct Queens$Queens *)($t0 = &(*this$)))->class$->placeQueen, $t4($t0, (c + 1))) ) {
                    return 1;
                } 
                ($t3 = ((struct Queens$Queens *)($t0 = &(*this$)))->class$->setRowColumn, $t3($t0, r, c, 1));
            } 
            r = (r + 1);
        } else {
            break;
        }
    }
    return 0;
}

uint8_t Queens$Queens$getRowColumn(void* this, int32_t r, int32_t c) {
    struct Queens$Queens* this$ = this;
    struct OBX$Array$1* $t0;
    struct OBX$Array$1* $t1;
    struct OBX$Array$1* $t2;
    return (((((uint8_t *)((struct OBX$Array$1){8,1,(*this$).freeRows}).$a)[r]) && (((uint8_t *)((struct OBX$Array$1){16,1,(*this$).freeMaxs}).$a)[(c + r)])) && (((uint8_t *)((struct OBX$Array$1){16,1,(*this$).freeMins}).$a)[((c - r) + 7)]));
}

void Queens$Queens$setRowColumn(void* this, int32_t r, int32_t c, uint8_t v) {
    struct Queens$Queens* this$ = this;
    struct OBX$Array$1* $t0;
    (((uint8_t *)((struct OBX$Array$1){8,1,(*this$).freeRows}).$a)[r]) = v;
    (((uint8_t *)((struct OBX$Array$1){16,1,(*this$).freeMaxs}).$a)[(c + r)]) = v;
    (((uint8_t *)((struct OBX$Array$1){16,1,(*this$).freeMins}).$a)[((c - r) + 7)]) = v;
}

uint8_t Queens$Queens$verifyResult(void* this, struct Benchmark$Result * result) {
    struct Queens$Queens* this$ = this;
    return (*((struct Benchmark$BoolResult*)result)).res;
}

struct Queens$Queens$Class$ Queens$Queens$class$ = { 
    &Benchmark$Benchmark$class$,
    Queens$Queens$benchmark,
    Queens$Queens$verifyResult,
    Benchmark$Benchmark$innerBenchmarkLoop,
    Queens$Queens$queens,
    Queens$Queens$placeQueen,
    Queens$Queens$getRowColumn,
    Queens$Queens$setRowColumn,
};

static int initDone$ = 0;
void Queens$init$(void) {
    if(initDone$) return; else initDone$ = 1;
    Benchmark$init$();
}
OBX$Cmd Queens$cmd$(const char* name) {
    if( name == 0 ) return Queens$init$;
    return 0;
}
