#ifndef _SOM$INTERFACES$017CF6702E_
#define _SOM$INTERFACES$017CF6702E_

// Generated by Oberon+ IDE (Mono) 0.9.106 on 2024-07-13T01:26:30

#include "OBX.Runtime.h"

// Declaration of module som.Interfaces(som.RedBlackTree(CD2.Vector2D,som.Vector(CD2.Motion).Vector).Entry)

struct som$RedBlackTree$c4a1631837$Entry;
struct som$RedBlackTree$c4a1631837$Entry; // meta actual
struct som$Interfaces$017cf6702e$ForEachInterfaceRW$Class$;
struct som$Interfaces$017cf6702e$ForEachInterfaceRW;
struct som$Interfaces$017cf6702e$TestInterface$Class$;
struct som$Interfaces$017cf6702e$TestInterface;
struct som$Interfaces$017cf6702e$Comparator$Class$;
struct som$Interfaces$017cf6702e$Comparator;
struct som$Interfaces$017cf6702e$ForEachInterface$Class$;
struct som$Interfaces$017cf6702e$ForEachInterface;
struct som$Interfaces$017cf6702e$ForEachInterfaceRW {
    struct som$Interfaces$017cf6702e$ForEachInterfaceRW$Class$* class$;
};

extern void som$Interfaces$017cf6702e$ForEachInterfaceRW$init$(struct som$Interfaces$017cf6702e$ForEachInterfaceRW*);
struct som$Interfaces$017cf6702e$TestInterface {
    struct som$Interfaces$017cf6702e$TestInterface$Class$* class$;
};

extern void som$Interfaces$017cf6702e$TestInterface$init$(struct som$Interfaces$017cf6702e$TestInterface*);
struct som$Interfaces$017cf6702e$Comparator {
    struct som$Interfaces$017cf6702e$Comparator$Class$* class$;
};

extern void som$Interfaces$017cf6702e$Comparator$init$(struct som$Interfaces$017cf6702e$Comparator*);
struct som$Interfaces$017cf6702e$ForEachInterface {
    struct som$Interfaces$017cf6702e$ForEachInterface$Class$* class$;
};

extern void som$Interfaces$017cf6702e$ForEachInterface$init$(struct som$Interfaces$017cf6702e$ForEachInterface*);
void som$Interfaces$017cf6702e$ForEachInterface$apply(void* this, struct som$RedBlackTree$c4a1631837$Entry * elem);
void som$Interfaces$017cf6702e$ForEachInterfaceRW$apply(void* this, struct som$RedBlackTree$c4a1631837$Entry * elem);
uint8_t som$Interfaces$017cf6702e$TestInterface$test(void* this, struct som$RedBlackTree$c4a1631837$Entry * elem);
int32_t som$Interfaces$017cf6702e$Comparator$compare(void* this, struct som$RedBlackTree$c4a1631837$Entry * i, struct som$RedBlackTree$c4a1631837$Entry * j);
struct som$Interfaces$017cf6702e$ForEachInterfaceRW$Class$ {
    struct som$Interfaces$017cf6702e$ForEachInterfaceRW$Class$* super$;
    void (*apply)(void* this, struct som$RedBlackTree$c4a1631837$Entry * elem);
};
extern struct som$Interfaces$017cf6702e$ForEachInterfaceRW$Class$ som$Interfaces$017cf6702e$ForEachInterfaceRW$class$;

struct som$Interfaces$017cf6702e$TestInterface$Class$ {
    struct som$Interfaces$017cf6702e$TestInterface$Class$* super$;
    uint8_t (*test)(void* this, struct som$RedBlackTree$c4a1631837$Entry * elem);
};
extern struct som$Interfaces$017cf6702e$TestInterface$Class$ som$Interfaces$017cf6702e$TestInterface$class$;

struct som$Interfaces$017cf6702e$Comparator$Class$ {
    struct som$Interfaces$017cf6702e$Comparator$Class$* super$;
    int32_t (*compare)(void* this, struct som$RedBlackTree$c4a1631837$Entry * i, struct som$RedBlackTree$c4a1631837$Entry * j);
};
extern struct som$Interfaces$017cf6702e$Comparator$Class$ som$Interfaces$017cf6702e$Comparator$class$;

struct som$Interfaces$017cf6702e$ForEachInterface$Class$ {
    struct som$Interfaces$017cf6702e$ForEachInterface$Class$* super$;
    void (*apply)(void* this, struct som$RedBlackTree$c4a1631837$Entry * elem);
};
extern struct som$Interfaces$017cf6702e$ForEachInterface$Class$ som$Interfaces$017cf6702e$ForEachInterface$class$;

extern void som$Interfaces$017cf6702e$init$(void);
extern OBX$Cmd som$Interfaces$017cf6702e$cmd$(const char* name);
#endif
