#ifndef _SOM$INTERFACES$1C1B29CF70_
#define _SOM$INTERFACES$1C1B29CF70_

// Generated by Oberon+ IDE (Mono) 0.9.106 on 2024-07-13T01:26:30

#include "OBX.Runtime.h"

// Declaration of module som.Interfaces(CD2.Collision)

struct CD2$Collision; // meta actual
struct som$Interfaces$1c1b29cf70$ForEachInterface$Class$;
struct som$Interfaces$1c1b29cf70$ForEachInterface;
struct som$Interfaces$1c1b29cf70$ForEachInterfaceRW$Class$;
struct som$Interfaces$1c1b29cf70$ForEachInterfaceRW;
struct som$Interfaces$1c1b29cf70$TestInterface$Class$;
struct som$Interfaces$1c1b29cf70$TestInterface;
struct som$Interfaces$1c1b29cf70$Comparator$Class$;
struct som$Interfaces$1c1b29cf70$Comparator;
struct som$Interfaces$1c1b29cf70$ForEachInterface {
    struct som$Interfaces$1c1b29cf70$ForEachInterface$Class$* class$;
};

extern void som$Interfaces$1c1b29cf70$ForEachInterface$init$(struct som$Interfaces$1c1b29cf70$ForEachInterface*);
struct som$Interfaces$1c1b29cf70$ForEachInterfaceRW {
    struct som$Interfaces$1c1b29cf70$ForEachInterfaceRW$Class$* class$;
};

extern void som$Interfaces$1c1b29cf70$ForEachInterfaceRW$init$(struct som$Interfaces$1c1b29cf70$ForEachInterfaceRW*);
struct som$Interfaces$1c1b29cf70$TestInterface {
    struct som$Interfaces$1c1b29cf70$TestInterface$Class$* class$;
};

extern void som$Interfaces$1c1b29cf70$TestInterface$init$(struct som$Interfaces$1c1b29cf70$TestInterface*);
struct som$Interfaces$1c1b29cf70$Comparator {
    struct som$Interfaces$1c1b29cf70$Comparator$Class$* class$;
};

extern void som$Interfaces$1c1b29cf70$Comparator$init$(struct som$Interfaces$1c1b29cf70$Comparator*);
void som$Interfaces$1c1b29cf70$ForEachInterface$apply(void* this, struct CD2$Collision * * elem);
void som$Interfaces$1c1b29cf70$ForEachInterfaceRW$apply(void* this, struct CD2$Collision * * elem);
uint8_t som$Interfaces$1c1b29cf70$TestInterface$test(void* this, struct CD2$Collision * * elem);
int32_t som$Interfaces$1c1b29cf70$Comparator$compare(void* this, struct CD2$Collision * * i, struct CD2$Collision * * j);
struct som$Interfaces$1c1b29cf70$ForEachInterface$Class$ {
    struct som$Interfaces$1c1b29cf70$ForEachInterface$Class$* super$;
    void (*apply)(void* this, struct CD2$Collision * * elem);
};
extern struct som$Interfaces$1c1b29cf70$ForEachInterface$Class$ som$Interfaces$1c1b29cf70$ForEachInterface$class$;

struct som$Interfaces$1c1b29cf70$ForEachInterfaceRW$Class$ {
    struct som$Interfaces$1c1b29cf70$ForEachInterfaceRW$Class$* super$;
    void (*apply)(void* this, struct CD2$Collision * * elem);
};
extern struct som$Interfaces$1c1b29cf70$ForEachInterfaceRW$Class$ som$Interfaces$1c1b29cf70$ForEachInterfaceRW$class$;

struct som$Interfaces$1c1b29cf70$TestInterface$Class$ {
    struct som$Interfaces$1c1b29cf70$TestInterface$Class$* super$;
    uint8_t (*test)(void* this, struct CD2$Collision * * elem);
};
extern struct som$Interfaces$1c1b29cf70$TestInterface$Class$ som$Interfaces$1c1b29cf70$TestInterface$class$;

struct som$Interfaces$1c1b29cf70$Comparator$Class$ {
    struct som$Interfaces$1c1b29cf70$Comparator$Class$* super$;
    int32_t (*compare)(void* this, struct CD2$Collision * * i, struct CD2$Collision * * j);
};
extern struct som$Interfaces$1c1b29cf70$Comparator$Class$ som$Interfaces$1c1b29cf70$Comparator$class$;

extern void som$Interfaces$1c1b29cf70$init$(void);
extern OBX$Cmd som$Interfaces$1c1b29cf70$cmd$(const char* name);
#endif
