#ifndef _SOM$INTERFACES$A1BE3657F7_
#define _SOM$INTERFACES$A1BE3657F7_

// Generated by Oberon+ IDE (Mono) 0.9.106 on 2024-07-13T01:26:30

#include "OBX.Runtime.h"

// Declaration of module som.Interfaces(CD.CallSign)

struct CD$CallSign;
struct CD$CallSign; // meta actual
struct som$Interfaces$a1be3657f7$TestInterface$Class$;
struct som$Interfaces$a1be3657f7$TestInterface;
struct som$Interfaces$a1be3657f7$ForEachInterface$Class$;
struct som$Interfaces$a1be3657f7$ForEachInterface;
struct som$Interfaces$a1be3657f7$ForEachInterfaceRW$Class$;
struct som$Interfaces$a1be3657f7$ForEachInterfaceRW;
struct som$Interfaces$a1be3657f7$Comparator$Class$;
struct som$Interfaces$a1be3657f7$Comparator;
struct som$Interfaces$a1be3657f7$TestInterface {
    struct som$Interfaces$a1be3657f7$TestInterface$Class$* class$;
};

extern void som$Interfaces$a1be3657f7$TestInterface$init$(struct som$Interfaces$a1be3657f7$TestInterface*);
struct som$Interfaces$a1be3657f7$ForEachInterface {
    struct som$Interfaces$a1be3657f7$ForEachInterface$Class$* class$;
};

extern void som$Interfaces$a1be3657f7$ForEachInterface$init$(struct som$Interfaces$a1be3657f7$ForEachInterface*);
struct som$Interfaces$a1be3657f7$ForEachInterfaceRW {
    struct som$Interfaces$a1be3657f7$ForEachInterfaceRW$Class$* class$;
};

extern void som$Interfaces$a1be3657f7$ForEachInterfaceRW$init$(struct som$Interfaces$a1be3657f7$ForEachInterfaceRW*);
struct som$Interfaces$a1be3657f7$Comparator {
    struct som$Interfaces$a1be3657f7$Comparator$Class$* class$;
};

extern void som$Interfaces$a1be3657f7$Comparator$init$(struct som$Interfaces$a1be3657f7$Comparator*);
void som$Interfaces$a1be3657f7$ForEachInterface$apply(void* this, struct CD$CallSign * elem);
void som$Interfaces$a1be3657f7$ForEachInterfaceRW$apply(void* this, struct CD$CallSign * elem);
uint8_t som$Interfaces$a1be3657f7$TestInterface$test(void* this, struct CD$CallSign * elem);
int32_t som$Interfaces$a1be3657f7$Comparator$compare(void* this, struct CD$CallSign * i, struct CD$CallSign * j);
struct som$Interfaces$a1be3657f7$TestInterface$Class$ {
    struct som$Interfaces$a1be3657f7$TestInterface$Class$* super$;
    uint8_t (*test)(void* this, struct CD$CallSign * elem);
};
extern struct som$Interfaces$a1be3657f7$TestInterface$Class$ som$Interfaces$a1be3657f7$TestInterface$class$;

struct som$Interfaces$a1be3657f7$ForEachInterface$Class$ {
    struct som$Interfaces$a1be3657f7$ForEachInterface$Class$* super$;
    void (*apply)(void* this, struct CD$CallSign * elem);
};
extern struct som$Interfaces$a1be3657f7$ForEachInterface$Class$ som$Interfaces$a1be3657f7$ForEachInterface$class$;

struct som$Interfaces$a1be3657f7$ForEachInterfaceRW$Class$ {
    struct som$Interfaces$a1be3657f7$ForEachInterfaceRW$Class$* super$;
    void (*apply)(void* this, struct CD$CallSign * elem);
};
extern struct som$Interfaces$a1be3657f7$ForEachInterfaceRW$Class$ som$Interfaces$a1be3657f7$ForEachInterfaceRW$class$;

struct som$Interfaces$a1be3657f7$Comparator$Class$ {
    struct som$Interfaces$a1be3657f7$Comparator$Class$* super$;
    int32_t (*compare)(void* this, struct CD$CallSign * i, struct CD$CallSign * j);
};
extern struct som$Interfaces$a1be3657f7$Comparator$Class$ som$Interfaces$a1be3657f7$Comparator$class$;

extern void som$Interfaces$a1be3657f7$init$(void);
extern OBX$Cmd som$Interfaces$a1be3657f7$cmd$(const char* name);
#endif
