#ifndef _SOM$INTERFACES$B3330A6A65_
#define _SOM$INTERFACES$B3330A6A65_

// Generated by Oberon+ IDE (Mono) 0.9.106 on 2024-07-13T01:26:30

#include "OBX.Runtime.h"

// Declaration of module som.Interfaces(som.RedBlackTree(CD.CallSign,CD.Vector3D).Entry)

struct som$RedBlackTree$80265c2f3b$Entry;
struct som$RedBlackTree$80265c2f3b$Entry; // meta actual
struct som$Interfaces$b3330a6a65$Comparator$Class$;
struct som$Interfaces$b3330a6a65$Comparator;
struct som$Interfaces$b3330a6a65$ForEachInterfaceRW$Class$;
struct som$Interfaces$b3330a6a65$ForEachInterfaceRW;
struct som$Interfaces$b3330a6a65$TestInterface$Class$;
struct som$Interfaces$b3330a6a65$TestInterface;
struct som$Interfaces$b3330a6a65$ForEachInterface$Class$;
struct som$Interfaces$b3330a6a65$ForEachInterface;
struct som$Interfaces$b3330a6a65$Comparator {
    struct som$Interfaces$b3330a6a65$Comparator$Class$* class$;
};

extern void som$Interfaces$b3330a6a65$Comparator$init$(struct som$Interfaces$b3330a6a65$Comparator*);
struct som$Interfaces$b3330a6a65$ForEachInterfaceRW {
    struct som$Interfaces$b3330a6a65$ForEachInterfaceRW$Class$* class$;
};

extern void som$Interfaces$b3330a6a65$ForEachInterfaceRW$init$(struct som$Interfaces$b3330a6a65$ForEachInterfaceRW*);
struct som$Interfaces$b3330a6a65$TestInterface {
    struct som$Interfaces$b3330a6a65$TestInterface$Class$* class$;
};

extern void som$Interfaces$b3330a6a65$TestInterface$init$(struct som$Interfaces$b3330a6a65$TestInterface*);
struct som$Interfaces$b3330a6a65$ForEachInterface {
    struct som$Interfaces$b3330a6a65$ForEachInterface$Class$* class$;
};

extern void som$Interfaces$b3330a6a65$ForEachInterface$init$(struct som$Interfaces$b3330a6a65$ForEachInterface*);
void som$Interfaces$b3330a6a65$ForEachInterface$apply(void* this, struct som$RedBlackTree$80265c2f3b$Entry * elem);
void som$Interfaces$b3330a6a65$ForEachInterfaceRW$apply(void* this, struct som$RedBlackTree$80265c2f3b$Entry * elem);
uint8_t som$Interfaces$b3330a6a65$TestInterface$test(void* this, struct som$RedBlackTree$80265c2f3b$Entry * elem);
int32_t som$Interfaces$b3330a6a65$Comparator$compare(void* this, struct som$RedBlackTree$80265c2f3b$Entry * i, struct som$RedBlackTree$80265c2f3b$Entry * j);
struct som$Interfaces$b3330a6a65$Comparator$Class$ {
    struct som$Interfaces$b3330a6a65$Comparator$Class$* super$;
    int32_t (*compare)(void* this, struct som$RedBlackTree$80265c2f3b$Entry * i, struct som$RedBlackTree$80265c2f3b$Entry * j);
};
extern struct som$Interfaces$b3330a6a65$Comparator$Class$ som$Interfaces$b3330a6a65$Comparator$class$;

struct som$Interfaces$b3330a6a65$ForEachInterfaceRW$Class$ {
    struct som$Interfaces$b3330a6a65$ForEachInterfaceRW$Class$* super$;
    void (*apply)(void* this, struct som$RedBlackTree$80265c2f3b$Entry * elem);
};
extern struct som$Interfaces$b3330a6a65$ForEachInterfaceRW$Class$ som$Interfaces$b3330a6a65$ForEachInterfaceRW$class$;

struct som$Interfaces$b3330a6a65$TestInterface$Class$ {
    struct som$Interfaces$b3330a6a65$TestInterface$Class$* super$;
    uint8_t (*test)(void* this, struct som$RedBlackTree$80265c2f3b$Entry * elem);
};
extern struct som$Interfaces$b3330a6a65$TestInterface$Class$ som$Interfaces$b3330a6a65$TestInterface$class$;

struct som$Interfaces$b3330a6a65$ForEachInterface$Class$ {
    struct som$Interfaces$b3330a6a65$ForEachInterface$Class$* super$;
    void (*apply)(void* this, struct som$RedBlackTree$80265c2f3b$Entry * elem);
};
extern struct som$Interfaces$b3330a6a65$ForEachInterface$Class$ som$Interfaces$b3330a6a65$ForEachInterface$class$;

extern void som$Interfaces$b3330a6a65$init$(void);
extern OBX$Cmd som$Interfaces$b3330a6a65$cmd$(const char* name);
#endif
