#ifndef _SOM$VECTOR$D424285281_
#define _SOM$VECTOR$D424285281_

// Generated by Oberon+ IDE (Mono) 0.9.106 on 2024-07-13T01:26:30

#include "OBX.Runtime.h"
#include "som.Interfaces.d424285281.h"

// Declaration of module som.Vector(CD2.Motion)

struct CD2$Motion; // meta actual
struct som$Vector$d424285281$Vector$Class$;
struct som$Vector$d424285281$Vector;
struct som$Vector$d424285281$Vector {
    struct som$Vector$d424285281$Vector$Class$* class$;
    struct OBX$Array$1 storage;
    int32_t firstIdx;
    int32_t lastIdx;
};

extern void som$Vector$d424285281$Vector$init$(struct som$Vector$d424285281$Vector*);
struct som$Vector$d424285281$Vector * som$Vector$d424285281$createWithSize(int32_t siz);
struct som$Vector$d424285281$Vector * som$Vector$d424285281$create();
struct som$Vector$d424285281$Vector * som$Vector$d424285281$createWithElement(struct CD2$Motion * * elem);
struct CD2$Motion * som$Vector$d424285281$Vector$at(void* this, int32_t idx);
void som$Vector$d424285281$Vector$resize(void* this, int32_t newLength);
void som$Vector$d424285281$Vector$atPut(void* this, int32_t idx, struct CD2$Motion * * elem);
void som$Vector$d424285281$Vector$append(void* this, struct CD2$Motion * * elem);
uint8_t som$Vector$d424285281$Vector$isEmpty(void* this);
struct CD2$Motion * som$Vector$d424285281$Vector$first(void* this);
struct CD2$Motion * som$Vector$d424285281$Vector$removeFirst(void* this);
void som$Vector$d424285281$Vector$removeAll(void* this);
int32_t som$Vector$d424285281$Vector$getSize(void* this);
int32_t som$Vector$d424285281$Vector$capacity(void* this);
void som$Vector$d424285281$Vector$forEach(void* this, struct som$Interfaces$d424285281$ForEachInterface * fn);
uint8_t som$Vector$d424285281$Vector$hasSome(void* this, struct som$Interfaces$d424285281$TestInterface * fn);
uint8_t som$Vector$d424285281$Vector$getOne(void* this, struct som$Interfaces$d424285281$TestInterface * fn, struct CD2$Motion * * out);
uint8_t som$Vector$d424285281$Vector$remove(void* this, struct CD2$Motion * * obj, uint8_t (*eq)(struct CD2$Motion * *, struct CD2$Motion * *));
void som$Vector$d424285281$Vector$sort(void* this, struct som$Interfaces$d424285281$Comparator * c);
void som$Vector$d424285281$Vector$sortImp(void* this, int32_t i, int32_t j, struct som$Interfaces$d424285281$Comparator * c);
void som$Vector$d424285281$swap(struct OBX$Array$1 storage2, int32_t i, int32_t j);
struct som$Vector$d424285281$Vector$Class$ {
    struct som$Vector$d424285281$Vector$Class$* super$;
    struct CD2$Motion * (*at)(void* this, int32_t idx);
    void (*resize)(void* this, int32_t newLength);
    void (*atPut)(void* this, int32_t idx, struct CD2$Motion * * elem);
    void (*append)(void* this, struct CD2$Motion * * elem);
    uint8_t (*isEmpty)(void* this);
    struct CD2$Motion * (*first)(void* this);
    struct CD2$Motion * (*removeFirst)(void* this);
    void (*removeAll)(void* this);
    int32_t (*getSize)(void* this);
    int32_t (*capacity)(void* this);
    void (*forEach)(void* this, struct som$Interfaces$d424285281$ForEachInterface * fn);
    uint8_t (*hasSome)(void* this, struct som$Interfaces$d424285281$TestInterface * fn);
    uint8_t (*getOne)(void* this, struct som$Interfaces$d424285281$TestInterface * fn, struct CD2$Motion * * out);
    uint8_t (*remove)(void* this, struct CD2$Motion * * obj, uint8_t (*eq)(struct CD2$Motion * *, struct CD2$Motion * *));
    void (*sort)(void* this, struct som$Interfaces$d424285281$Comparator * c);
    void (*sortImp)(void* this, int32_t i, int32_t j, struct som$Interfaces$d424285281$Comparator * c);
};
extern struct som$Vector$d424285281$Vector$Class$ som$Vector$d424285281$Vector$class$;

extern void som$Vector$d424285281$init$(void);
extern OBX$Cmd som$Vector$d424285281$cmd$(const char* name);
#endif
