#ifndef _SOM$VECTOR$BCCC871B36_
#define _SOM$VECTOR$BCCC871B36_

// Generated by Oberon+ IDE (Mono) 0.9.106 on 2024-07-13T01:26:30

#include "OBX.Runtime.h"
#include "som.Interfaces.bccc871b36.h"

// Declaration of module som.Vector(som.Vector(INT32).Vector)

struct som$Vector$04445da84e$Vector; // meta actual
struct som$Vector$bccc871b36$Vector$Class$;
struct som$Vector$bccc871b36$Vector;
struct som$Vector$bccc871b36$Vector {
    struct som$Vector$bccc871b36$Vector$Class$* class$;
    struct OBX$Array$1 storage;
    int32_t firstIdx;
    int32_t lastIdx;
};

extern void som$Vector$bccc871b36$Vector$init$(struct som$Vector$bccc871b36$Vector*);
struct som$Vector$bccc871b36$Vector * som$Vector$bccc871b36$createWithSize(int32_t siz);
struct som$Vector$bccc871b36$Vector * som$Vector$bccc871b36$create();
struct som$Vector$bccc871b36$Vector * som$Vector$bccc871b36$createWithElement(struct som$Vector$04445da84e$Vector * * elem);
struct som$Vector$04445da84e$Vector * som$Vector$bccc871b36$Vector$at(void* this, int32_t idx);
void som$Vector$bccc871b36$Vector$resize(void* this, int32_t newLength);
void som$Vector$bccc871b36$Vector$atPut(void* this, int32_t idx, struct som$Vector$04445da84e$Vector * * elem);
void som$Vector$bccc871b36$Vector$append(void* this, struct som$Vector$04445da84e$Vector * * elem);
uint8_t som$Vector$bccc871b36$Vector$isEmpty(void* this);
struct som$Vector$04445da84e$Vector * som$Vector$bccc871b36$Vector$first(void* this);
struct som$Vector$04445da84e$Vector * som$Vector$bccc871b36$Vector$removeFirst(void* this);
void som$Vector$bccc871b36$Vector$removeAll(void* this);
int32_t som$Vector$bccc871b36$Vector$getSize(void* this);
int32_t som$Vector$bccc871b36$Vector$capacity(void* this);
void som$Vector$bccc871b36$Vector$forEach(void* this, struct som$Interfaces$bccc871b36$ForEachInterface * fn);
uint8_t som$Vector$bccc871b36$Vector$hasSome(void* this, struct som$Interfaces$bccc871b36$TestInterface * fn);
uint8_t som$Vector$bccc871b36$Vector$getOne(void* this, struct som$Interfaces$bccc871b36$TestInterface * fn, struct som$Vector$04445da84e$Vector * * out);
uint8_t som$Vector$bccc871b36$Vector$remove(void* this, struct som$Vector$04445da84e$Vector * * obj, uint8_t (*eq)(struct som$Vector$04445da84e$Vector * *, struct som$Vector$04445da84e$Vector * *));
void som$Vector$bccc871b36$Vector$sort(void* this, struct som$Interfaces$bccc871b36$Comparator * c);
void som$Vector$bccc871b36$Vector$sortImp(void* this, int32_t i, int32_t j, struct som$Interfaces$bccc871b36$Comparator * c);
void som$Vector$bccc871b36$swap(struct OBX$Array$1 storage2, int32_t i, int32_t j);
struct som$Vector$bccc871b36$Vector$Class$ {
    struct som$Vector$bccc871b36$Vector$Class$* super$;
    struct som$Vector$04445da84e$Vector * (*at)(void* this, int32_t idx);
    void (*resize)(void* this, int32_t newLength);
    void (*atPut)(void* this, int32_t idx, struct som$Vector$04445da84e$Vector * * elem);
    void (*append)(void* this, struct som$Vector$04445da84e$Vector * * elem);
    uint8_t (*isEmpty)(void* this);
    struct som$Vector$04445da84e$Vector * (*first)(void* this);
    struct som$Vector$04445da84e$Vector * (*removeFirst)(void* this);
    void (*removeAll)(void* this);
    int32_t (*getSize)(void* this);
    int32_t (*capacity)(void* this);
    void (*forEach)(void* this, struct som$Interfaces$bccc871b36$ForEachInterface * fn);
    uint8_t (*hasSome)(void* this, struct som$Interfaces$bccc871b36$TestInterface * fn);
    uint8_t (*getOne)(void* this, struct som$Interfaces$bccc871b36$TestInterface * fn, struct som$Vector$04445da84e$Vector * * out);
    uint8_t (*remove)(void* this, struct som$Vector$04445da84e$Vector * * obj, uint8_t (*eq)(struct som$Vector$04445da84e$Vector * *, struct som$Vector$04445da84e$Vector * *));
    void (*sort)(void* this, struct som$Interfaces$bccc871b36$Comparator * c);
    void (*sortImp)(void* this, int32_t i, int32_t j, struct som$Interfaces$bccc871b36$Comparator * c);
};
extern struct som$Vector$bccc871b36$Vector$Class$ som$Vector$bccc871b36$Vector$class$;

extern void som$Vector$bccc871b36$init$(void);
extern OBX$Cmd som$Vector$bccc871b36$cmd$(const char* name);
#endif
