#ifndef _SOM$IDENTITYDICTIONARY$84B2AA0859_
#define _SOM$IDENTITYDICTIONARY$84B2AA0859_

// Generated by Oberon+ IDE (Mono) 0.9.106 on 2024-07-13T01:26:30

#include "OBX.Runtime.h"
#include "som.Dictionary.84b2aa0859.h"

// Declaration of module som.IdentityDictionary(Havlak.BasicBlock,INT32)

struct Havlak$BasicBlock; // meta actual
struct som$Dictionary$84b2aa0859$Dictionary * som$IdentityDictionary$84b2aa0859$create(int32_t (*hf)(struct Havlak$BasicBlock * *));
struct som$Dictionary$84b2aa0859$Dictionary * som$IdentityDictionary$84b2aa0859$createWithSize(int32_t size, int32_t (*hf)(struct Havlak$BasicBlock * *));
extern void som$IdentityDictionary$84b2aa0859$init$(void);
extern OBX$Cmd som$IdentityDictionary$84b2aa0859$cmd$(const char* name);
#endif
