// Generated by Oberon+ IDE (Mono) 0.9.106 on 2024-07-13T01:26:30

#include "som.Random.h"

int32_t som$Random$seed = 0;
int32_t som$Random$next() {
    som$Random$seed = (((som$Random$seed * 1309) + 13849) & 65535);
    return som$Random$seed;
}

void som$Random$reset() {
    som$Random$seed = 74755;
}

static int initDone$ = 0;
void som$Random$init$(void) {
    if(initDone$) return; else initDone$ = 1;
    som$Random$reset();
}
OBX$Cmd som$Random$cmd$(const char* name) {
    if( name == 0 ) return som$Random$init$;
    if( strcmp(name,"reset") == 0 ) return som$Random$reset;
    return 0;
}
