// Generated by Oberon+ IDE (Mono) 0.9.106 on 2024-07-13T01:26:30

#include "som.Interfaces.1f9e73b9b7.h"
#include "som.Vector.1f9e73b9b7.h"

void som$Interfaces$1f9e73b9b7$ForEachInterface$init$(struct som$Interfaces$1f9e73b9b7$ForEachInterface* inst){
    inst->class$ = &som$Interfaces$1f9e73b9b7$ForEachInterface$class$;
}
void som$Interfaces$1f9e73b9b7$ForEachInterfaceRW$init$(struct som$Interfaces$1f9e73b9b7$ForEachInterfaceRW* inst){
    inst->class$ = &som$Interfaces$1f9e73b9b7$ForEachInterfaceRW$class$;
}
void som$Interfaces$1f9e73b9b7$Comparator$init$(struct som$Interfaces$1f9e73b9b7$Comparator* inst){
    inst->class$ = &som$Interfaces$1f9e73b9b7$Comparator$class$;
}
void som$Interfaces$1f9e73b9b7$TestInterface$init$(struct som$Interfaces$1f9e73b9b7$TestInterface* inst){
    inst->class$ = &som$Interfaces$1f9e73b9b7$TestInterface$class$;
}
void som$Interfaces$1f9e73b9b7$ForEachInterface$apply(void* this, struct DeltaBlue$Sym * * elem) {
    struct som$Interfaces$1f9e73b9b7$ForEachInterface* this$ = this;
}

void som$Interfaces$1f9e73b9b7$ForEachInterfaceRW$apply(void* this, struct DeltaBlue$Sym * * elem) {
    struct som$Interfaces$1f9e73b9b7$ForEachInterfaceRW* this$ = this;
}

uint8_t som$Interfaces$1f9e73b9b7$TestInterface$test(void* this, struct DeltaBlue$Sym * * elem) {
    struct som$Interfaces$1f9e73b9b7$TestInterface* this$ = this;
    return 0;
}

int32_t som$Interfaces$1f9e73b9b7$Comparator$compare(void* this, struct DeltaBlue$Sym * * i, struct DeltaBlue$Sym * * j) {
    struct som$Interfaces$1f9e73b9b7$Comparator* this$ = this;
    return 0;
}

struct som$Interfaces$1f9e73b9b7$ForEachInterface$Class$ som$Interfaces$1f9e73b9b7$ForEachInterface$class$ = { 
    0,
    som$Interfaces$1f9e73b9b7$ForEachInterface$apply,
};

struct som$Interfaces$1f9e73b9b7$ForEachInterfaceRW$Class$ som$Interfaces$1f9e73b9b7$ForEachInterfaceRW$class$ = { 
    0,
    som$Interfaces$1f9e73b9b7$ForEachInterfaceRW$apply,
};

struct som$Interfaces$1f9e73b9b7$Comparator$Class$ som$Interfaces$1f9e73b9b7$Comparator$class$ = { 
    0,
    som$Interfaces$1f9e73b9b7$Comparator$compare,
};

struct som$Interfaces$1f9e73b9b7$TestInterface$Class$ som$Interfaces$1f9e73b9b7$TestInterface$class$ = { 
    0,
    som$Interfaces$1f9e73b9b7$TestInterface$test,
};

static int initDone$ = 0;
void som$Interfaces$1f9e73b9b7$init$(void) {
    if(initDone$) return; else initDone$ = 1;
}
OBX$Cmd som$Interfaces$1f9e73b9b7$cmd$(const char* name) {
    if( name == 0 ) return som$Interfaces$1f9e73b9b7$init$;
    return 0;
}
