#ifndef _SOM$SET$6226D61315_
#define _SOM$SET$6226D61315_

// Generated by Oberon+ IDE (Mono) 0.9.106 on 2024-07-13T01:26:30

#include "OBX.Runtime.h"
#include "som.Vector.6226d61315.h"
#include "som.Interfaces.6226d61315.h"

// Declaration of module som.Set(Havlak.BasicBlock)

struct Havlak$BasicBlock; // meta actual
struct som$Set$6226d61315$Set$Class$;
struct som$Set$6226d61315$Set;
struct som$Set$6226d61315$Set$contains$TestInterface$Class$;
struct som$Set$6226d61315$Set$contains$TestInterface;
struct som$Set$6226d61315$Set {
    struct som$Set$6226d61315$Set$Class$* class$;
    struct som$Vector$6226d61315$Vector * items;
};

extern void som$Set$6226d61315$Set$init$(struct som$Set$6226d61315$Set*);
struct som$Set$6226d61315$Set$contains$TestInterface {
    struct som$Set$6226d61315$Set$contains$TestInterface$Class$* class$;
    struct Havlak$BasicBlock * obj;
};

extern void som$Set$6226d61315$Set$contains$TestInterface$init$(struct som$Set$6226d61315$Set$contains$TestInterface*);
struct som$Set$6226d61315$Set * som$Set$6226d61315$createWithSize(int32_t siz);
struct som$Set$6226d61315$Set * som$Set$6226d61315$create();
int32_t som$Set$6226d61315$Set$getSize(void* this);
void som$Set$6226d61315$Set$forEach(void* this, struct som$Interfaces$6226d61315$ForEachInterface * fn);
uint8_t som$Set$6226d61315$Set$hasSome(void* this, struct som$Interfaces$6226d61315$TestInterface * fn);
uint8_t som$Set$6226d61315$Set$getOne(void* this, struct som$Interfaces$6226d61315$TestInterface * fn, struct Havlak$BasicBlock * * out);
void som$Set$6226d61315$Set$removeAll(void* this);
void som$Set$6226d61315$Set$add(void* this, struct Havlak$BasicBlock * * obj);
uint8_t som$Set$6226d61315$Set$contains(void* this, struct Havlak$BasicBlock * * obj);
uint8_t som$Set$6226d61315$Set$contains$TestInterface$test(void* this, struct Havlak$BasicBlock * * elem);
struct som$Set$6226d61315$Set$Class$ {
    struct som$Set$6226d61315$Set$Class$* super$;
    int32_t (*getSize)(void* this);
    void (*forEach)(void* this, struct som$Interfaces$6226d61315$ForEachInterface * fn);
    uint8_t (*hasSome)(void* this, struct som$Interfaces$6226d61315$TestInterface * fn);
    uint8_t (*getOne)(void* this, struct som$Interfaces$6226d61315$TestInterface * fn, struct Havlak$BasicBlock * * out);
    void (*removeAll)(void* this);
    void (*add)(void* this, struct Havlak$BasicBlock * * obj);
    uint8_t (*contains)(void* this, struct Havlak$BasicBlock * * obj);
};
extern struct som$Set$6226d61315$Set$Class$ som$Set$6226d61315$Set$class$;

struct som$Set$6226d61315$Set$contains$TestInterface$Class$ {
    struct som$Interfaces$6226d61315$TestInterface$Class$* super$;
    uint8_t (*test)(void* this, struct Havlak$BasicBlock * * elem);
};
extern struct som$Set$6226d61315$Set$contains$TestInterface$Class$ som$Set$6226d61315$Set$contains$TestInterface$class$;

extern void som$Set$6226d61315$init$(void);
extern OBX$Cmd som$Set$6226d61315$cmd$(const char* name);
#endif
