#ifndef _SOM$INTERFACES$57F847CD33_
#define _SOM$INTERFACES$57F847CD33_

// Generated by Oberon+ IDE (Mono) 0.9.106 on 2024-07-13T01:26:30

#include "OBX.Runtime.h"

// Declaration of module som.Interfaces(som.RedBlackTree(CD2.CallSign,CD2.Vector3D).Entry)

struct som$RedBlackTree$1a37460855$Entry;
struct som$RedBlackTree$1a37460855$Entry; // meta actual
struct som$Interfaces$57f847cd33$Comparator$Class$;
struct som$Interfaces$57f847cd33$Comparator;
struct som$Interfaces$57f847cd33$TestInterface$Class$;
struct som$Interfaces$57f847cd33$TestInterface;
struct som$Interfaces$57f847cd33$ForEachInterfaceRW$Class$;
struct som$Interfaces$57f847cd33$ForEachInterfaceRW;
struct som$Interfaces$57f847cd33$ForEachInterface$Class$;
struct som$Interfaces$57f847cd33$ForEachInterface;
struct som$Interfaces$57f847cd33$Comparator {
    struct som$Interfaces$57f847cd33$Comparator$Class$* class$;
};

extern void som$Interfaces$57f847cd33$Comparator$init$(struct som$Interfaces$57f847cd33$Comparator*);
struct som$Interfaces$57f847cd33$TestInterface {
    struct som$Interfaces$57f847cd33$TestInterface$Class$* class$;
};

extern void som$Interfaces$57f847cd33$TestInterface$init$(struct som$Interfaces$57f847cd33$TestInterface*);
struct som$Interfaces$57f847cd33$ForEachInterfaceRW {
    struct som$Interfaces$57f847cd33$ForEachInterfaceRW$Class$* class$;
};

extern void som$Interfaces$57f847cd33$ForEachInterfaceRW$init$(struct som$Interfaces$57f847cd33$ForEachInterfaceRW*);
struct som$Interfaces$57f847cd33$ForEachInterface {
    struct som$Interfaces$57f847cd33$ForEachInterface$Class$* class$;
};

extern void som$Interfaces$57f847cd33$ForEachInterface$init$(struct som$Interfaces$57f847cd33$ForEachInterface*);
void som$Interfaces$57f847cd33$ForEachInterface$apply(void* this, struct som$RedBlackTree$1a37460855$Entry * elem);
void som$Interfaces$57f847cd33$ForEachInterfaceRW$apply(void* this, struct som$RedBlackTree$1a37460855$Entry * elem);
uint8_t som$Interfaces$57f847cd33$TestInterface$test(void* this, struct som$RedBlackTree$1a37460855$Entry * elem);
int32_t som$Interfaces$57f847cd33$Comparator$compare(void* this, struct som$RedBlackTree$1a37460855$Entry * i, struct som$RedBlackTree$1a37460855$Entry * j);
struct som$Interfaces$57f847cd33$Comparator$Class$ {
    struct som$Interfaces$57f847cd33$Comparator$Class$* super$;
    int32_t (*compare)(void* this, struct som$RedBlackTree$1a37460855$Entry * i, struct som$RedBlackTree$1a37460855$Entry * j);
};
extern struct som$Interfaces$57f847cd33$Comparator$Class$ som$Interfaces$57f847cd33$Comparator$class$;

struct som$Interfaces$57f847cd33$TestInterface$Class$ {
    struct som$Interfaces$57f847cd33$TestInterface$Class$* super$;
    uint8_t (*test)(void* this, struct som$RedBlackTree$1a37460855$Entry * elem);
};
extern struct som$Interfaces$57f847cd33$TestInterface$Class$ som$Interfaces$57f847cd33$TestInterface$class$;

struct som$Interfaces$57f847cd33$ForEachInterfaceRW$Class$ {
    struct som$Interfaces$57f847cd33$ForEachInterfaceRW$Class$* super$;
    void (*apply)(void* this, struct som$RedBlackTree$1a37460855$Entry * elem);
};
extern struct som$Interfaces$57f847cd33$ForEachInterfaceRW$Class$ som$Interfaces$57f847cd33$ForEachInterfaceRW$class$;

struct som$Interfaces$57f847cd33$ForEachInterface$Class$ {
    struct som$Interfaces$57f847cd33$ForEachInterface$Class$* super$;
    void (*apply)(void* this, struct som$RedBlackTree$1a37460855$Entry * elem);
};
extern struct som$Interfaces$57f847cd33$ForEachInterface$Class$ som$Interfaces$57f847cd33$ForEachInterface$class$;

extern void som$Interfaces$57f847cd33$init$(void);
extern OBX$Cmd som$Interfaces$57f847cd33$cmd$(const char* name);
#endif
