#ifndef _SOM$VECTOR$AD6C2C594A_
#define _SOM$VECTOR$AD6C2C594A_

// Generated by Oberon+ IDE (Mono) 0.9.106 on 2024-07-13T01:26:30

#include "OBX.Runtime.h"
#include "som.Interfaces.ad6c2c594a.h"

// Declaration of module som.Vector(DeltaBlue.AbstractConstraint)

struct DeltaBlue$AbstractConstraint; // meta actual
struct som$Vector$ad6c2c594a$Vector$Class$;
struct som$Vector$ad6c2c594a$Vector;
struct som$Vector$ad6c2c594a$Vector {
    struct som$Vector$ad6c2c594a$Vector$Class$* class$;
    struct OBX$Array$1 storage;
    int32_t firstIdx;
    int32_t lastIdx;
};

extern void som$Vector$ad6c2c594a$Vector$init$(struct som$Vector$ad6c2c594a$Vector*);
struct som$Vector$ad6c2c594a$Vector * som$Vector$ad6c2c594a$createWithSize(int32_t siz);
struct som$Vector$ad6c2c594a$Vector * som$Vector$ad6c2c594a$create();
struct som$Vector$ad6c2c594a$Vector * som$Vector$ad6c2c594a$createWithElement(struct DeltaBlue$AbstractConstraint * * elem);
struct DeltaBlue$AbstractConstraint * som$Vector$ad6c2c594a$Vector$at(void* this, int32_t idx);
void som$Vector$ad6c2c594a$Vector$resize(void* this, int32_t newLength);
void som$Vector$ad6c2c594a$Vector$atPut(void* this, int32_t idx, struct DeltaBlue$AbstractConstraint * * elem);
void som$Vector$ad6c2c594a$Vector$append(void* this, struct DeltaBlue$AbstractConstraint * * elem);
uint8_t som$Vector$ad6c2c594a$Vector$isEmpty(void* this);
struct DeltaBlue$AbstractConstraint * som$Vector$ad6c2c594a$Vector$first(void* this);
struct DeltaBlue$AbstractConstraint * som$Vector$ad6c2c594a$Vector$removeFirst(void* this);
void som$Vector$ad6c2c594a$Vector$removeAll(void* this);
int32_t som$Vector$ad6c2c594a$Vector$getSize(void* this);
int32_t som$Vector$ad6c2c594a$Vector$capacity(void* this);
void som$Vector$ad6c2c594a$Vector$forEach(void* this, struct som$Interfaces$ad6c2c594a$ForEachInterface * fn);
uint8_t som$Vector$ad6c2c594a$Vector$hasSome(void* this, struct som$Interfaces$ad6c2c594a$TestInterface * fn);
uint8_t som$Vector$ad6c2c594a$Vector$getOne(void* this, struct som$Interfaces$ad6c2c594a$TestInterface * fn, struct DeltaBlue$AbstractConstraint * * out);
uint8_t som$Vector$ad6c2c594a$Vector$remove(void* this, struct DeltaBlue$AbstractConstraint * * obj, uint8_t (*eq)(struct DeltaBlue$AbstractConstraint * *, struct DeltaBlue$AbstractConstraint * *));
void som$Vector$ad6c2c594a$Vector$sort(void* this, struct som$Interfaces$ad6c2c594a$Comparator * c);
void som$Vector$ad6c2c594a$Vector$sortImp(void* this, int32_t i, int32_t j, struct som$Interfaces$ad6c2c594a$Comparator * c);
void som$Vector$ad6c2c594a$swap(struct OBX$Array$1 storage2, int32_t i, int32_t j);
struct som$Vector$ad6c2c594a$Vector$Class$ {
    struct som$Vector$ad6c2c594a$Vector$Class$* super$;
    struct DeltaBlue$AbstractConstraint * (*at)(void* this, int32_t idx);
    void (*resize)(void* this, int32_t newLength);
    void (*atPut)(void* this, int32_t idx, struct DeltaBlue$AbstractConstraint * * elem);
    void (*append)(void* this, struct DeltaBlue$AbstractConstraint * * elem);
    uint8_t (*isEmpty)(void* this);
    struct DeltaBlue$AbstractConstraint * (*first)(void* this);
    struct DeltaBlue$AbstractConstraint * (*removeFirst)(void* this);
    void (*removeAll)(void* this);
    int32_t (*getSize)(void* this);
    int32_t (*capacity)(void* this);
    void (*forEach)(void* this, struct som$Interfaces$ad6c2c594a$ForEachInterface * fn);
    uint8_t (*hasSome)(void* this, struct som$Interfaces$ad6c2c594a$TestInterface * fn);
    uint8_t (*getOne)(void* this, struct som$Interfaces$ad6c2c594a$TestInterface * fn, struct DeltaBlue$AbstractConstraint * * out);
    uint8_t (*remove)(void* this, struct DeltaBlue$AbstractConstraint * * obj, uint8_t (*eq)(struct DeltaBlue$AbstractConstraint * *, struct DeltaBlue$AbstractConstraint * *));
    void (*sort)(void* this, struct som$Interfaces$ad6c2c594a$Comparator * c);
    void (*sortImp)(void* this, int32_t i, int32_t j, struct som$Interfaces$ad6c2c594a$Comparator * c);
};
extern struct som$Vector$ad6c2c594a$Vector$Class$ som$Vector$ad6c2c594a$Vector$class$;

extern void som$Vector$ad6c2c594a$init$(void);
extern OBX$Cmd som$Vector$ad6c2c594a$cmd$(const char* name);
#endif
