#ifndef _SOM$INTERFACES$6184042AEF_
#define _SOM$INTERFACES$6184042AEF_

// Generated by Oberon+ IDE (Mono) 0.9.106 on 2024-07-13T01:26:30

#include "OBX.Runtime.h"

// Declaration of module som.Interfaces(Havlak.BasicBlockEdge)

struct Havlak$BasicBlockEdge; // meta actual
struct som$Interfaces$6184042aef$ForEachInterface$Class$;
struct som$Interfaces$6184042aef$ForEachInterface;
struct som$Interfaces$6184042aef$Comparator$Class$;
struct som$Interfaces$6184042aef$Comparator;
struct som$Interfaces$6184042aef$ForEachInterfaceRW$Class$;
struct som$Interfaces$6184042aef$ForEachInterfaceRW;
struct som$Interfaces$6184042aef$TestInterface$Class$;
struct som$Interfaces$6184042aef$TestInterface;
struct som$Interfaces$6184042aef$ForEachInterface {
    struct som$Interfaces$6184042aef$ForEachInterface$Class$* class$;
};

extern void som$Interfaces$6184042aef$ForEachInterface$init$(struct som$Interfaces$6184042aef$ForEachInterface*);
struct som$Interfaces$6184042aef$Comparator {
    struct som$Interfaces$6184042aef$Comparator$Class$* class$;
};

extern void som$Interfaces$6184042aef$Comparator$init$(struct som$Interfaces$6184042aef$Comparator*);
struct som$Interfaces$6184042aef$ForEachInterfaceRW {
    struct som$Interfaces$6184042aef$ForEachInterfaceRW$Class$* class$;
};

extern void som$Interfaces$6184042aef$ForEachInterfaceRW$init$(struct som$Interfaces$6184042aef$ForEachInterfaceRW*);
struct som$Interfaces$6184042aef$TestInterface {
    struct som$Interfaces$6184042aef$TestInterface$Class$* class$;
};

extern void som$Interfaces$6184042aef$TestInterface$init$(struct som$Interfaces$6184042aef$TestInterface*);
void som$Interfaces$6184042aef$ForEachInterface$apply(void* this, struct Havlak$BasicBlockEdge * * elem);
void som$Interfaces$6184042aef$ForEachInterfaceRW$apply(void* this, struct Havlak$BasicBlockEdge * * elem);
uint8_t som$Interfaces$6184042aef$TestInterface$test(void* this, struct Havlak$BasicBlockEdge * * elem);
int32_t som$Interfaces$6184042aef$Comparator$compare(void* this, struct Havlak$BasicBlockEdge * * i, struct Havlak$BasicBlockEdge * * j);
struct som$Interfaces$6184042aef$ForEachInterface$Class$ {
    struct som$Interfaces$6184042aef$ForEachInterface$Class$* super$;
    void (*apply)(void* this, struct Havlak$BasicBlockEdge * * elem);
};
extern struct som$Interfaces$6184042aef$ForEachInterface$Class$ som$Interfaces$6184042aef$ForEachInterface$class$;

struct som$Interfaces$6184042aef$Comparator$Class$ {
    struct som$Interfaces$6184042aef$Comparator$Class$* super$;
    int32_t (*compare)(void* this, struct Havlak$BasicBlockEdge * * i, struct Havlak$BasicBlockEdge * * j);
};
extern struct som$Interfaces$6184042aef$Comparator$Class$ som$Interfaces$6184042aef$Comparator$class$;

struct som$Interfaces$6184042aef$ForEachInterfaceRW$Class$ {
    struct som$Interfaces$6184042aef$ForEachInterfaceRW$Class$* super$;
    void (*apply)(void* this, struct Havlak$BasicBlockEdge * * elem);
};
extern struct som$Interfaces$6184042aef$ForEachInterfaceRW$Class$ som$Interfaces$6184042aef$ForEachInterfaceRW$class$;

struct som$Interfaces$6184042aef$TestInterface$Class$ {
    struct som$Interfaces$6184042aef$TestInterface$Class$* super$;
    uint8_t (*test)(void* this, struct Havlak$BasicBlockEdge * * elem);
};
extern struct som$Interfaces$6184042aef$TestInterface$Class$ som$Interfaces$6184042aef$TestInterface$class$;

extern void som$Interfaces$6184042aef$init$(void);
extern OBX$Cmd som$Interfaces$6184042aef$cmd$(const char* name);
#endif
