// Generated by Oberon+ IDE (Mono) 0.9.106 on 2024-07-13T01:26:30

#include "som.Interfaces.bccc871b36.h"
#include "som.Vector.bccc871b36.h"

void som$Interfaces$bccc871b36$TestInterface$init$(struct som$Interfaces$bccc871b36$TestInterface* inst){
    inst->class$ = &som$Interfaces$bccc871b36$TestInterface$class$;
}
void som$Interfaces$bccc871b36$ForEachInterface$init$(struct som$Interfaces$bccc871b36$ForEachInterface* inst){
    inst->class$ = &som$Interfaces$bccc871b36$ForEachInterface$class$;
}
void som$Interfaces$bccc871b36$ForEachInterfaceRW$init$(struct som$Interfaces$bccc871b36$ForEachInterfaceRW* inst){
    inst->class$ = &som$Interfaces$bccc871b36$ForEachInterfaceRW$class$;
}
void som$Interfaces$bccc871b36$Comparator$init$(struct som$Interfaces$bccc871b36$Comparator* inst){
    inst->class$ = &som$Interfaces$bccc871b36$Comparator$class$;
}
void som$Interfaces$bccc871b36$ForEachInterface$apply(void* this, struct som$Vector$04445da84e$Vector * * elem) {
    struct som$Interfaces$bccc871b36$ForEachInterface* this$ = this;
}

void som$Interfaces$bccc871b36$ForEachInterfaceRW$apply(void* this, struct som$Vector$04445da84e$Vector * * elem) {
    struct som$Interfaces$bccc871b36$ForEachInterfaceRW* this$ = this;
}

uint8_t som$Interfaces$bccc871b36$TestInterface$test(void* this, struct som$Vector$04445da84e$Vector * * elem) {
    struct som$Interfaces$bccc871b36$TestInterface* this$ = this;
    return 0;
}

int32_t som$Interfaces$bccc871b36$Comparator$compare(void* this, struct som$Vector$04445da84e$Vector * * i, struct som$Vector$04445da84e$Vector * * j) {
    struct som$Interfaces$bccc871b36$Comparator* this$ = this;
    return 0;
}

struct som$Interfaces$bccc871b36$TestInterface$Class$ som$Interfaces$bccc871b36$TestInterface$class$ = { 
    0,
    som$Interfaces$bccc871b36$TestInterface$test,
};

struct som$Interfaces$bccc871b36$ForEachInterface$Class$ som$Interfaces$bccc871b36$ForEachInterface$class$ = { 
    0,
    som$Interfaces$bccc871b36$ForEachInterface$apply,
};

struct som$Interfaces$bccc871b36$ForEachInterfaceRW$Class$ som$Interfaces$bccc871b36$ForEachInterfaceRW$class$ = { 
    0,
    som$Interfaces$bccc871b36$ForEachInterfaceRW$apply,
};

struct som$Interfaces$bccc871b36$Comparator$Class$ som$Interfaces$bccc871b36$Comparator$class$ = { 
    0,
    som$Interfaces$bccc871b36$Comparator$compare,
};

static int initDone$ = 0;
void som$Interfaces$bccc871b36$init$(void) {
    if(initDone$) return; else initDone$ = 1;
}
OBX$Cmd som$Interfaces$bccc871b36$cmd$(const char* name) {
    if( name == 0 ) return som$Interfaces$bccc871b36$init$;
    return 0;
}
