#ifndef _SOM$INTERFACES$7850AFF62D_
#define _SOM$INTERFACES$7850AFF62D_

// Generated by Oberon+ IDE (Mono) 0.9.106 on 2024-07-13T01:26:30

#include "OBX.Runtime.h"

// Declaration of module som.Interfaces(DeltaBlue.Variable)

struct DeltaBlue$Variable; // meta actual
struct som$Interfaces$7850aff62d$ForEachInterfaceRW$Class$;
struct som$Interfaces$7850aff62d$ForEachInterfaceRW;
struct som$Interfaces$7850aff62d$Comparator$Class$;
struct som$Interfaces$7850aff62d$Comparator;
struct som$Interfaces$7850aff62d$TestInterface$Class$;
struct som$Interfaces$7850aff62d$TestInterface;
struct som$Interfaces$7850aff62d$ForEachInterface$Class$;
struct som$Interfaces$7850aff62d$ForEachInterface;
struct som$Interfaces$7850aff62d$ForEachInterfaceRW {
    struct som$Interfaces$7850aff62d$ForEachInterfaceRW$Class$* class$;
};

extern void som$Interfaces$7850aff62d$ForEachInterfaceRW$init$(struct som$Interfaces$7850aff62d$ForEachInterfaceRW*);
struct som$Interfaces$7850aff62d$Comparator {
    struct som$Interfaces$7850aff62d$Comparator$Class$* class$;
};

extern void som$Interfaces$7850aff62d$Comparator$init$(struct som$Interfaces$7850aff62d$Comparator*);
struct som$Interfaces$7850aff62d$TestInterface {
    struct som$Interfaces$7850aff62d$TestInterface$Class$* class$;
};

extern void som$Interfaces$7850aff62d$TestInterface$init$(struct som$Interfaces$7850aff62d$TestInterface*);
struct som$Interfaces$7850aff62d$ForEachInterface {
    struct som$Interfaces$7850aff62d$ForEachInterface$Class$* class$;
};

extern void som$Interfaces$7850aff62d$ForEachInterface$init$(struct som$Interfaces$7850aff62d$ForEachInterface*);
void som$Interfaces$7850aff62d$ForEachInterface$apply(void* this, struct DeltaBlue$Variable * * elem);
void som$Interfaces$7850aff62d$ForEachInterfaceRW$apply(void* this, struct DeltaBlue$Variable * * elem);
uint8_t som$Interfaces$7850aff62d$TestInterface$test(void* this, struct DeltaBlue$Variable * * elem);
int32_t som$Interfaces$7850aff62d$Comparator$compare(void* this, struct DeltaBlue$Variable * * i, struct DeltaBlue$Variable * * j);
struct som$Interfaces$7850aff62d$ForEachInterfaceRW$Class$ {
    struct som$Interfaces$7850aff62d$ForEachInterfaceRW$Class$* super$;
    void (*apply)(void* this, struct DeltaBlue$Variable * * elem);
};
extern struct som$Interfaces$7850aff62d$ForEachInterfaceRW$Class$ som$Interfaces$7850aff62d$ForEachInterfaceRW$class$;

struct som$Interfaces$7850aff62d$Comparator$Class$ {
    struct som$Interfaces$7850aff62d$Comparator$Class$* super$;
    int32_t (*compare)(void* this, struct DeltaBlue$Variable * * i, struct DeltaBlue$Variable * * j);
};
extern struct som$Interfaces$7850aff62d$Comparator$Class$ som$Interfaces$7850aff62d$Comparator$class$;

struct som$Interfaces$7850aff62d$TestInterface$Class$ {
    struct som$Interfaces$7850aff62d$TestInterface$Class$* super$;
    uint8_t (*test)(void* this, struct DeltaBlue$Variable * * elem);
};
extern struct som$Interfaces$7850aff62d$TestInterface$Class$ som$Interfaces$7850aff62d$TestInterface$class$;

struct som$Interfaces$7850aff62d$ForEachInterface$Class$ {
    struct som$Interfaces$7850aff62d$ForEachInterface$Class$* super$;
    void (*apply)(void* this, struct DeltaBlue$Variable * * elem);
};
extern struct som$Interfaces$7850aff62d$ForEachInterface$Class$ som$Interfaces$7850aff62d$ForEachInterface$class$;

extern void som$Interfaces$7850aff62d$init$(void);
extern OBX$Cmd som$Interfaces$7850aff62d$cmd$(const char* name);
#endif
