// Generated by Oberon+ IDE (Mono) 0.9.106 on 2024-07-13T01:26:30

#include "som.Interfaces.d424285281.h"
#include "som.Vector.d424285281.h"

void som$Interfaces$d424285281$ForEachInterface$init$(struct som$Interfaces$d424285281$ForEachInterface* inst){
    inst->class$ = &som$Interfaces$d424285281$ForEachInterface$class$;
}
void som$Interfaces$d424285281$ForEachInterfaceRW$init$(struct som$Interfaces$d424285281$ForEachInterfaceRW* inst){
    inst->class$ = &som$Interfaces$d424285281$ForEachInterfaceRW$class$;
}
void som$Interfaces$d424285281$Comparator$init$(struct som$Interfaces$d424285281$Comparator* inst){
    inst->class$ = &som$Interfaces$d424285281$Comparator$class$;
}
void som$Interfaces$d424285281$TestInterface$init$(struct som$Interfaces$d424285281$TestInterface* inst){
    inst->class$ = &som$Interfaces$d424285281$TestInterface$class$;
}
void som$Interfaces$d424285281$ForEachInterface$apply(void* this, struct CD2$Motion * * elem) {
    struct som$Interfaces$d424285281$ForEachInterface* this$ = this;
}

void som$Interfaces$d424285281$ForEachInterfaceRW$apply(void* this, struct CD2$Motion * * elem) {
    struct som$Interfaces$d424285281$ForEachInterfaceRW* this$ = this;
}

uint8_t som$Interfaces$d424285281$TestInterface$test(void* this, struct CD2$Motion * * elem) {
    struct som$Interfaces$d424285281$TestInterface* this$ = this;
    return 0;
}

int32_t som$Interfaces$d424285281$Comparator$compare(void* this, struct CD2$Motion * * i, struct CD2$Motion * * j) {
    struct som$Interfaces$d424285281$Comparator* this$ = this;
    return 0;
}

struct som$Interfaces$d424285281$ForEachInterface$Class$ som$Interfaces$d424285281$ForEachInterface$class$ = { 
    0,
    som$Interfaces$d424285281$ForEachInterface$apply,
};

struct som$Interfaces$d424285281$ForEachInterfaceRW$Class$ som$Interfaces$d424285281$ForEachInterfaceRW$class$ = { 
    0,
    som$Interfaces$d424285281$ForEachInterfaceRW$apply,
};

struct som$Interfaces$d424285281$Comparator$Class$ som$Interfaces$d424285281$Comparator$class$ = { 
    0,
    som$Interfaces$d424285281$Comparator$compare,
};

struct som$Interfaces$d424285281$TestInterface$Class$ som$Interfaces$d424285281$TestInterface$class$ = { 
    0,
    som$Interfaces$d424285281$TestInterface$test,
};

static int initDone$ = 0;
void som$Interfaces$d424285281$init$(void) {
    if(initDone$) return; else initDone$ = 1;
}
OBX$Cmd som$Interfaces$d424285281$cmd$(const char* name) {
    if( name == 0 ) return som$Interfaces$d424285281$init$;
    return 0;
}
