#ifndef _SOM$VECTOR$6184042AEF_
#define _SOM$VECTOR$6184042AEF_

// Generated by Oberon+ IDE (Mono) 0.9.106 on 2024-07-13T01:26:30

#include "OBX.Runtime.h"
#include "som.Interfaces.6184042aef.h"

// Declaration of module som.Vector(Havlak.BasicBlockEdge)

struct Havlak$BasicBlockEdge; // meta actual
struct som$Vector$6184042aef$Vector$Class$;
struct som$Vector$6184042aef$Vector;
struct som$Vector$6184042aef$Vector {
    struct som$Vector$6184042aef$Vector$Class$* class$;
    struct OBX$Array$1 storage;
    int32_t firstIdx;
    int32_t lastIdx;
};

extern void som$Vector$6184042aef$Vector$init$(struct som$Vector$6184042aef$Vector*);
struct som$Vector$6184042aef$Vector * som$Vector$6184042aef$createWithSize(int32_t siz);
struct som$Vector$6184042aef$Vector * som$Vector$6184042aef$create();
struct som$Vector$6184042aef$Vector * som$Vector$6184042aef$createWithElement(struct Havlak$BasicBlockEdge * * elem);
struct Havlak$BasicBlockEdge * som$Vector$6184042aef$Vector$at(void* this, int32_t idx);
void som$Vector$6184042aef$Vector$resize(void* this, int32_t newLength);
void som$Vector$6184042aef$Vector$atPut(void* this, int32_t idx, struct Havlak$BasicBlockEdge * * elem);
void som$Vector$6184042aef$Vector$append(void* this, struct Havlak$BasicBlockEdge * * elem);
uint8_t som$Vector$6184042aef$Vector$isEmpty(void* this);
struct Havlak$BasicBlockEdge * som$Vector$6184042aef$Vector$first(void* this);
struct Havlak$BasicBlockEdge * som$Vector$6184042aef$Vector$removeFirst(void* this);
void som$Vector$6184042aef$Vector$removeAll(void* this);
int32_t som$Vector$6184042aef$Vector$getSize(void* this);
int32_t som$Vector$6184042aef$Vector$capacity(void* this);
void som$Vector$6184042aef$Vector$forEach(void* this, struct som$Interfaces$6184042aef$ForEachInterface * fn);
uint8_t som$Vector$6184042aef$Vector$hasSome(void* this, struct som$Interfaces$6184042aef$TestInterface * fn);
uint8_t som$Vector$6184042aef$Vector$getOne(void* this, struct som$Interfaces$6184042aef$TestInterface * fn, struct Havlak$BasicBlockEdge * * out);
uint8_t som$Vector$6184042aef$Vector$remove(void* this, struct Havlak$BasicBlockEdge * * obj, uint8_t (*eq)(struct Havlak$BasicBlockEdge * *, struct Havlak$BasicBlockEdge * *));
void som$Vector$6184042aef$Vector$sort(void* this, struct som$Interfaces$6184042aef$Comparator * c);
void som$Vector$6184042aef$Vector$sortImp(void* this, int32_t i, int32_t j, struct som$Interfaces$6184042aef$Comparator * c);
void som$Vector$6184042aef$swap(struct OBX$Array$1 storage2, int32_t i, int32_t j);
struct som$Vector$6184042aef$Vector$Class$ {
    struct som$Vector$6184042aef$Vector$Class$* super$;
    struct Havlak$BasicBlockEdge * (*at)(void* this, int32_t idx);
    void (*resize)(void* this, int32_t newLength);
    void (*atPut)(void* this, int32_t idx, struct Havlak$BasicBlockEdge * * elem);
    void (*append)(void* this, struct Havlak$BasicBlockEdge * * elem);
    uint8_t (*isEmpty)(void* this);
    struct Havlak$BasicBlockEdge * (*first)(void* this);
    struct Havlak$BasicBlockEdge * (*removeFirst)(void* this);
    void (*removeAll)(void* this);
    int32_t (*getSize)(void* this);
    int32_t (*capacity)(void* this);
    void (*forEach)(void* this, struct som$Interfaces$6184042aef$ForEachInterface * fn);
    uint8_t (*hasSome)(void* this, struct som$Interfaces$6184042aef$TestInterface * fn);
    uint8_t (*getOne)(void* this, struct som$Interfaces$6184042aef$TestInterface * fn, struct Havlak$BasicBlockEdge * * out);
    uint8_t (*remove)(void* this, struct Havlak$BasicBlockEdge * * obj, uint8_t (*eq)(struct Havlak$BasicBlockEdge * *, struct Havlak$BasicBlockEdge * *));
    void (*sort)(void* this, struct som$Interfaces$6184042aef$Comparator * c);
    void (*sortImp)(void* this, int32_t i, int32_t j, struct som$Interfaces$6184042aef$Comparator * c);
};
extern struct som$Vector$6184042aef$Vector$Class$ som$Vector$6184042aef$Vector$class$;

extern void som$Vector$6184042aef$init$(void);
extern OBX$Cmd som$Vector$6184042aef$cmd$(const char* name);
#endif
