#ifndef _SOM$IDENTITYDICTIONARY2$DF63A5A394_
#define _SOM$IDENTITYDICTIONARY2$DF63A5A394_

// Generated by Oberon+ IDE (Mono) 0.9.106 on 2024-07-13T01:26:30

#include "OBX.Runtime.h"
#include "som.Dictionary2.5c466e54b6.h"

// Declaration of module som.IdentityDictionary2(DeltaBlue.Sym,INT32,DeltaBlue.symHash)

struct DeltaBlue$Sym; // meta actual
struct som$Dictionary2$5c466e54b6$Dictionary * som$IdentityDictionary2$df63a5a394$create();
struct som$Dictionary2$5c466e54b6$Dictionary * som$IdentityDictionary2$df63a5a394$createWithSize(int32_t size);
extern void som$IdentityDictionary2$df63a5a394$init$(void);
extern OBX$Cmd som$IdentityDictionary2$df63a5a394$cmd$(const char* name);
#endif
