#ifndef _SOM$REDBLACKTREE$80265C2F3B_
#define _SOM$REDBLACKTREE$80265C2F3B_

// Generated by Oberon+ IDE (Mono) 0.9.106 on 2024-07-13T01:26:30

#include "OBX.Runtime.h"
#include "som.Interfaces.b3330a6a65.h"

// Declaration of module som.RedBlackTree(CD.CallSign,CD.Vector3D)

struct CD$CallSign;
struct CD$Vector3D;
struct CD$CallSign; // meta actual
struct CD$Vector3D; // meta actual
struct som$RedBlackTree$80265c2f3b$InsertResult$Class$;
struct som$RedBlackTree$80265c2f3b$InsertResult;
struct som$RedBlackTree$80265c2f3b$Node$Class$;
struct som$RedBlackTree$80265c2f3b$Node;
struct som$RedBlackTree$80265c2f3b$Entry$Class$;
struct som$RedBlackTree$80265c2f3b$Entry;
struct som$RedBlackTree$80265c2f3b$RedBlackTree$Class$;
struct som$RedBlackTree$80265c2f3b$RedBlackTree;
struct som$RedBlackTree$80265c2f3b$InsertResult {
    struct som$RedBlackTree$80265c2f3b$InsertResult$Class$* class$;
    uint8_t isNewEntry;
    struct som$RedBlackTree$80265c2f3b$Node * newNode;
    struct /*CD$Vector3D*/ { void* class$; double x; double y; double z; } oldValue;
};

extern void som$RedBlackTree$80265c2f3b$InsertResult$init$(struct som$RedBlackTree$80265c2f3b$InsertResult*);
struct som$RedBlackTree$80265c2f3b$Node {
    struct som$RedBlackTree$80265c2f3b$Node$Class$* class$;
    struct /*CD$CallSign*/ { void* class$; int32_t value; } key;
    struct /*CD$Vector3D*/ { void* class$; double x; double y; double z; } value;
    struct som$RedBlackTree$80265c2f3b$Node * left;
    struct som$RedBlackTree$80265c2f3b$Node * right;
    struct som$RedBlackTree$80265c2f3b$Node * parent;
    int color;
};

extern void som$RedBlackTree$80265c2f3b$Node$init$(struct som$RedBlackTree$80265c2f3b$Node*);
struct som$RedBlackTree$80265c2f3b$Entry {
    struct som$RedBlackTree$80265c2f3b$Entry$Class$* class$;
    struct /*CD$CallSign*/ { void* class$; int32_t value; } key;
    struct /*CD$Vector3D*/ { void* class$; double x; double y; double z; } value;
};

extern void som$RedBlackTree$80265c2f3b$Entry$init$(struct som$RedBlackTree$80265c2f3b$Entry*);
struct som$RedBlackTree$80265c2f3b$RedBlackTree {
    struct som$RedBlackTree$80265c2f3b$RedBlackTree$Class$* class$;
    struct som$RedBlackTree$80265c2f3b$Node * root;
    int32_t (*compare)(struct CD$CallSign *, struct CD$CallSign *);
};

extern void som$RedBlackTree$80265c2f3b$RedBlackTree$init$(struct som$RedBlackTree$80265c2f3b$RedBlackTree*);
struct som$RedBlackTree$80265c2f3b$Node * som$RedBlackTree$80265c2f3b$createNode(struct CD$CallSign * key, struct CD$Vector3D * value);
struct som$RedBlackTree$80265c2f3b$Node * som$RedBlackTree$80265c2f3b$treeMinimum(struct som$RedBlackTree$80265c2f3b$Node * x);
struct som$RedBlackTree$80265c2f3b$Node * som$RedBlackTree$80265c2f3b$Node$successor(void* this);
struct som$RedBlackTree$80265c2f3b$RedBlackTree * som$RedBlackTree$80265c2f3b$create(int32_t (*func)(struct CD$CallSign *, struct CD$CallSign *));
struct CD$Vector3D som$RedBlackTree$80265c2f3b$RedBlackTree$put(void* this, struct CD$CallSign * key, struct CD$Vector3D * value);
struct CD$Vector3D som$RedBlackTree$80265c2f3b$RedBlackTree$putChecked(void* this, struct CD$CallSign * key, struct CD$Vector3D * value, uint8_t * newEntry);
struct CD$Vector3D som$RedBlackTree$80265c2f3b$RedBlackTree$remove(void* this, struct CD$CallSign * key);
struct CD$Vector3D som$RedBlackTree$80265c2f3b$RedBlackTree$get(void* this, struct CD$CallSign * key);
void som$RedBlackTree$80265c2f3b$RedBlackTree$forEach(void* this, struct som$Interfaces$b3330a6a65$ForEachInterface * fn);
struct som$RedBlackTree$80265c2f3b$Node * som$RedBlackTree$80265c2f3b$RedBlackTree$findNode(void* this, struct CD$CallSign * key);
void som$RedBlackTree$80265c2f3b$RedBlackTree$treeInsert(void* this, struct CD$CallSign * key, struct CD$Vector3D * value, struct som$RedBlackTree$80265c2f3b$InsertResult * res);
void som$RedBlackTree$80265c2f3b$RedBlackTree$leftRotate(void* this, struct som$RedBlackTree$80265c2f3b$Node * x);
void som$RedBlackTree$80265c2f3b$RedBlackTree$rightRotate(void* this, struct som$RedBlackTree$80265c2f3b$Node * y);
void som$RedBlackTree$80265c2f3b$RedBlackTree$removeFixup(void* this, struct som$RedBlackTree$80265c2f3b$Node * x, struct som$RedBlackTree$80265c2f3b$Node * xParent);
struct som$RedBlackTree$80265c2f3b$InsertResult$Class$ {
    struct som$RedBlackTree$80265c2f3b$InsertResult$Class$* super$;
};
extern struct som$RedBlackTree$80265c2f3b$InsertResult$Class$ som$RedBlackTree$80265c2f3b$InsertResult$class$;

struct som$RedBlackTree$80265c2f3b$Node$Class$ {
    struct som$RedBlackTree$80265c2f3b$Node$Class$* super$;
    struct som$RedBlackTree$80265c2f3b$Node * (*successor)(void* this);
};
extern struct som$RedBlackTree$80265c2f3b$Node$Class$ som$RedBlackTree$80265c2f3b$Node$class$;

struct som$RedBlackTree$80265c2f3b$Entry$Class$ {
    struct som$RedBlackTree$80265c2f3b$Entry$Class$* super$;
};
extern struct som$RedBlackTree$80265c2f3b$Entry$Class$ som$RedBlackTree$80265c2f3b$Entry$class$;

struct som$RedBlackTree$80265c2f3b$RedBlackTree$Class$ {
    struct som$RedBlackTree$80265c2f3b$RedBlackTree$Class$* super$;
    struct CD$Vector3D (*put)(void* this, struct CD$CallSign * key, struct CD$Vector3D * value);
    struct CD$Vector3D (*putChecked)(void* this, struct CD$CallSign * key, struct CD$Vector3D * value, uint8_t * newEntry);
    struct CD$Vector3D (*remove)(void* this, struct CD$CallSign * key);
    struct CD$Vector3D (*get)(void* this, struct CD$CallSign * key);
    void (*forEach)(void* this, struct som$Interfaces$b3330a6a65$ForEachInterface * fn);
    struct som$RedBlackTree$80265c2f3b$Node * (*findNode)(void* this, struct CD$CallSign * key);
    void (*treeInsert)(void* this, struct CD$CallSign * key, struct CD$Vector3D * value, struct som$RedBlackTree$80265c2f3b$InsertResult * res);
    void (*leftRotate)(void* this, struct som$RedBlackTree$80265c2f3b$Node * x);
    void (*rightRotate)(void* this, struct som$RedBlackTree$80265c2f3b$Node * y);
    void (*removeFixup)(void* this, struct som$RedBlackTree$80265c2f3b$Node * x, struct som$RedBlackTree$80265c2f3b$Node * xParent);
};
extern struct som$RedBlackTree$80265c2f3b$RedBlackTree$Class$ som$RedBlackTree$80265c2f3b$RedBlackTree$class$;

extern void som$RedBlackTree$80265c2f3b$init$(void);
extern OBX$Cmd som$RedBlackTree$80265c2f3b$cmd$(const char* name);
#endif
