// Generated by Oberon+ IDE (Mono) 0.9.106 on 2024-07-13T01:26:30

#include "som.Interfaces.326bd6ec32.h"
#include "som.Vector.326bd6ec32.h"

void som$Interfaces$326bd6ec32$ForEachInterface$init$(struct som$Interfaces$326bd6ec32$ForEachInterface* inst){
    inst->class$ = &som$Interfaces$326bd6ec32$ForEachInterface$class$;
}
void som$Interfaces$326bd6ec32$TestInterface$init$(struct som$Interfaces$326bd6ec32$TestInterface* inst){
    inst->class$ = &som$Interfaces$326bd6ec32$TestInterface$class$;
}
void som$Interfaces$326bd6ec32$Comparator$init$(struct som$Interfaces$326bd6ec32$Comparator* inst){
    inst->class$ = &som$Interfaces$326bd6ec32$Comparator$class$;
}
void som$Interfaces$326bd6ec32$ForEachInterfaceRW$init$(struct som$Interfaces$326bd6ec32$ForEachInterfaceRW* inst){
    inst->class$ = &som$Interfaces$326bd6ec32$ForEachInterfaceRW$class$;
}
void som$Interfaces$326bd6ec32$ForEachInterface$apply(void* this, struct CD$Collision * elem) {
    struct som$Interfaces$326bd6ec32$ForEachInterface* this$ = this;
}

void som$Interfaces$326bd6ec32$ForEachInterfaceRW$apply(void* this, struct CD$Collision * elem) {
    struct som$Interfaces$326bd6ec32$ForEachInterfaceRW* this$ = this;
}

uint8_t som$Interfaces$326bd6ec32$TestInterface$test(void* this, struct CD$Collision * elem) {
    struct som$Interfaces$326bd6ec32$TestInterface* this$ = this;
    return 0;
}

int32_t som$Interfaces$326bd6ec32$Comparator$compare(void* this, struct CD$Collision * i, struct CD$Collision * j) {
    struct som$Interfaces$326bd6ec32$Comparator* this$ = this;
    return 0;
}

struct som$Interfaces$326bd6ec32$ForEachInterface$Class$ som$Interfaces$326bd6ec32$ForEachInterface$class$ = { 
    0,
    som$Interfaces$326bd6ec32$ForEachInterface$apply,
};

struct som$Interfaces$326bd6ec32$TestInterface$Class$ som$Interfaces$326bd6ec32$TestInterface$class$ = { 
    0,
    som$Interfaces$326bd6ec32$TestInterface$test,
};

struct som$Interfaces$326bd6ec32$Comparator$Class$ som$Interfaces$326bd6ec32$Comparator$class$ = { 
    0,
    som$Interfaces$326bd6ec32$Comparator$compare,
};

struct som$Interfaces$326bd6ec32$ForEachInterfaceRW$Class$ som$Interfaces$326bd6ec32$ForEachInterfaceRW$class$ = { 
    0,
    som$Interfaces$326bd6ec32$ForEachInterfaceRW$apply,
};

static int initDone$ = 0;
void som$Interfaces$326bd6ec32$init$(void) {
    if(initDone$) return; else initDone$ = 1;
}
OBX$Cmd som$Interfaces$326bd6ec32$cmd$(const char* name) {
    if( name == 0 ) return som$Interfaces$326bd6ec32$init$;
    return 0;
}
