#ifndef _SOM$INTERFACES$D1517C3AA3_
#define _SOM$INTERFACES$D1517C3AA3_

// Generated by Oberon+ IDE (Mono) 0.9.106 on 2024-07-13T01:26:30

#include "OBX.Runtime.h"

// Declaration of module som.Interfaces(som.RedBlackTree(CD.Vector2D,som.Vector(CD.Motion).Vector).Entry)

struct som$RedBlackTree$14446907c4$Entry;
struct som$RedBlackTree$14446907c4$Entry; // meta actual
struct som$Interfaces$d1517c3aa3$ForEachInterface$Class$;
struct som$Interfaces$d1517c3aa3$ForEachInterface;
struct som$Interfaces$d1517c3aa3$ForEachInterfaceRW$Class$;
struct som$Interfaces$d1517c3aa3$ForEachInterfaceRW;
struct som$Interfaces$d1517c3aa3$TestInterface$Class$;
struct som$Interfaces$d1517c3aa3$TestInterface;
struct som$Interfaces$d1517c3aa3$Comparator$Class$;
struct som$Interfaces$d1517c3aa3$Comparator;
struct som$Interfaces$d1517c3aa3$ForEachInterface {
    struct som$Interfaces$d1517c3aa3$ForEachInterface$Class$* class$;
};

extern void som$Interfaces$d1517c3aa3$ForEachInterface$init$(struct som$Interfaces$d1517c3aa3$ForEachInterface*);
struct som$Interfaces$d1517c3aa3$ForEachInterfaceRW {
    struct som$Interfaces$d1517c3aa3$ForEachInterfaceRW$Class$* class$;
};

extern void som$Interfaces$d1517c3aa3$ForEachInterfaceRW$init$(struct som$Interfaces$d1517c3aa3$ForEachInterfaceRW*);
struct som$Interfaces$d1517c3aa3$TestInterface {
    struct som$Interfaces$d1517c3aa3$TestInterface$Class$* class$;
};

extern void som$Interfaces$d1517c3aa3$TestInterface$init$(struct som$Interfaces$d1517c3aa3$TestInterface*);
struct som$Interfaces$d1517c3aa3$Comparator {
    struct som$Interfaces$d1517c3aa3$Comparator$Class$* class$;
};

extern void som$Interfaces$d1517c3aa3$Comparator$init$(struct som$Interfaces$d1517c3aa3$Comparator*);
void som$Interfaces$d1517c3aa3$ForEachInterface$apply(void* this, struct som$RedBlackTree$14446907c4$Entry * elem);
void som$Interfaces$d1517c3aa3$ForEachInterfaceRW$apply(void* this, struct som$RedBlackTree$14446907c4$Entry * elem);
uint8_t som$Interfaces$d1517c3aa3$TestInterface$test(void* this, struct som$RedBlackTree$14446907c4$Entry * elem);
int32_t som$Interfaces$d1517c3aa3$Comparator$compare(void* this, struct som$RedBlackTree$14446907c4$Entry * i, struct som$RedBlackTree$14446907c4$Entry * j);
struct som$Interfaces$d1517c3aa3$ForEachInterface$Class$ {
    struct som$Interfaces$d1517c3aa3$ForEachInterface$Class$* super$;
    void (*apply)(void* this, struct som$RedBlackTree$14446907c4$Entry * elem);
};
extern struct som$Interfaces$d1517c3aa3$ForEachInterface$Class$ som$Interfaces$d1517c3aa3$ForEachInterface$class$;

struct som$Interfaces$d1517c3aa3$ForEachInterfaceRW$Class$ {
    struct som$Interfaces$d1517c3aa3$ForEachInterfaceRW$Class$* super$;
    void (*apply)(void* this, struct som$RedBlackTree$14446907c4$Entry * elem);
};
extern struct som$Interfaces$d1517c3aa3$ForEachInterfaceRW$Class$ som$Interfaces$d1517c3aa3$ForEachInterfaceRW$class$;

struct som$Interfaces$d1517c3aa3$TestInterface$Class$ {
    struct som$Interfaces$d1517c3aa3$TestInterface$Class$* super$;
    uint8_t (*test)(void* this, struct som$RedBlackTree$14446907c4$Entry * elem);
};
extern struct som$Interfaces$d1517c3aa3$TestInterface$Class$ som$Interfaces$d1517c3aa3$TestInterface$class$;

struct som$Interfaces$d1517c3aa3$Comparator$Class$ {
    struct som$Interfaces$d1517c3aa3$Comparator$Class$* super$;
    int32_t (*compare)(void* this, struct som$RedBlackTree$14446907c4$Entry * i, struct som$RedBlackTree$14446907c4$Entry * j);
};
extern struct som$Interfaces$d1517c3aa3$Comparator$Class$ som$Interfaces$d1517c3aa3$Comparator$class$;

extern void som$Interfaces$d1517c3aa3$init$(void);
extern OBX$Cmd som$Interfaces$d1517c3aa3$cmd$(const char* name);
#endif
