#ifndef _SOM$VECTOR$C92001DA8C_
#define _SOM$VECTOR$C92001DA8C_

// Generated by Oberon+ IDE (Mono) 0.9.106 on 2024-07-13T01:26:30

#include "OBX.Runtime.h"
#include "som.Interfaces.c92001da8c.h"

// Declaration of module som.Vector(Json.JsonValue)

struct Json$JsonValue; // meta actual
struct som$Vector$c92001da8c$Vector$Class$;
struct som$Vector$c92001da8c$Vector;
struct som$Vector$c92001da8c$Vector {
    struct som$Vector$c92001da8c$Vector$Class$* class$;
    struct OBX$Array$1 storage;
    int32_t firstIdx;
    int32_t lastIdx;
};

extern void som$Vector$c92001da8c$Vector$init$(struct som$Vector$c92001da8c$Vector*);
struct som$Vector$c92001da8c$Vector * som$Vector$c92001da8c$createWithSize(int32_t siz);
struct som$Vector$c92001da8c$Vector * som$Vector$c92001da8c$create();
struct som$Vector$c92001da8c$Vector * som$Vector$c92001da8c$createWithElement(struct Json$JsonValue * * elem);
struct Json$JsonValue * som$Vector$c92001da8c$Vector$at(void* this, int32_t idx);
void som$Vector$c92001da8c$Vector$resize(void* this, int32_t newLength);
void som$Vector$c92001da8c$Vector$atPut(void* this, int32_t idx, struct Json$JsonValue * * elem);
void som$Vector$c92001da8c$Vector$append(void* this, struct Json$JsonValue * * elem);
uint8_t som$Vector$c92001da8c$Vector$isEmpty(void* this);
struct Json$JsonValue * som$Vector$c92001da8c$Vector$first(void* this);
struct Json$JsonValue * som$Vector$c92001da8c$Vector$removeFirst(void* this);
void som$Vector$c92001da8c$Vector$removeAll(void* this);
int32_t som$Vector$c92001da8c$Vector$getSize(void* this);
int32_t som$Vector$c92001da8c$Vector$capacity(void* this);
void som$Vector$c92001da8c$Vector$forEach(void* this, struct som$Interfaces$c92001da8c$ForEachInterface * fn);
uint8_t som$Vector$c92001da8c$Vector$hasSome(void* this, struct som$Interfaces$c92001da8c$TestInterface * fn);
uint8_t som$Vector$c92001da8c$Vector$getOne(void* this, struct som$Interfaces$c92001da8c$TestInterface * fn, struct Json$JsonValue * * out);
uint8_t som$Vector$c92001da8c$Vector$remove(void* this, struct Json$JsonValue * * obj, uint8_t (*eq)(struct Json$JsonValue * *, struct Json$JsonValue * *));
void som$Vector$c92001da8c$Vector$sort(void* this, struct som$Interfaces$c92001da8c$Comparator * c);
void som$Vector$c92001da8c$Vector$sortImp(void* this, int32_t i, int32_t j, struct som$Interfaces$c92001da8c$Comparator * c);
void som$Vector$c92001da8c$swap(struct OBX$Array$1 storage2, int32_t i, int32_t j);
struct som$Vector$c92001da8c$Vector$Class$ {
    struct som$Vector$c92001da8c$Vector$Class$* super$;
    struct Json$JsonValue * (*at)(void* this, int32_t idx);
    void (*resize)(void* this, int32_t newLength);
    void (*atPut)(void* this, int32_t idx, struct Json$JsonValue * * elem);
    void (*append)(void* this, struct Json$JsonValue * * elem);
    uint8_t (*isEmpty)(void* this);
    struct Json$JsonValue * (*first)(void* this);
    struct Json$JsonValue * (*removeFirst)(void* this);
    void (*removeAll)(void* this);
    int32_t (*getSize)(void* this);
    int32_t (*capacity)(void* this);
    void (*forEach)(void* this, struct som$Interfaces$c92001da8c$ForEachInterface * fn);
    uint8_t (*hasSome)(void* this, struct som$Interfaces$c92001da8c$TestInterface * fn);
    uint8_t (*getOne)(void* this, struct som$Interfaces$c92001da8c$TestInterface * fn, struct Json$JsonValue * * out);
    uint8_t (*remove)(void* this, struct Json$JsonValue * * obj, uint8_t (*eq)(struct Json$JsonValue * *, struct Json$JsonValue * *));
    void (*sort)(void* this, struct som$Interfaces$c92001da8c$Comparator * c);
    void (*sortImp)(void* this, int32_t i, int32_t j, struct som$Interfaces$c92001da8c$Comparator * c);
};
extern struct som$Vector$c92001da8c$Vector$Class$ som$Vector$c92001da8c$Vector$class$;

extern void som$Vector$c92001da8c$init$(void);
extern OBX$Cmd som$Vector$c92001da8c$cmd$(const char* name);
#endif
