#ifndef _QUICK_
#define _QUICK_

// Generated by Oberon+ IDE (Mono) 0.9.107 on 2024-08-10T01:27:54

#include "OBX.Runtime.h"
#include "Util.h"

// Declaration of module Quick

extern int32_t Quick$sortlist[5001];
extern int32_t Quick$biggest;
extern int32_t Quick$littlest;
extern int32_t Quick$top;
void Quick$Initarr();
void Quick$Quicksort(struct OBX$Array$1 a, int32_t l, int32_t r);
void Quick$Run();
extern void Quick$init$(void);
extern OBX$Cmd Quick$cmd$(const char* name);
#endif
