#ifndef _TOWERS_
#define _TOWERS_

// Generated by Oberon+ IDE (Mono) 0.9.107 on 2024-08-10T01:27:54

#include "OBX.Runtime.h"
#include "Util.h"

// Declaration of module Towers

struct Towers$element$Class$;
struct Towers$element;
struct Towers$element {
    struct Towers$element$Class$* class$;
    int32_t discsize;
    int32_t next;
};

extern void Towers$element$init$(struct Towers$element*);
extern int32_t Towers$stack[4];
extern struct Towers$element Towers$cellspace[19];
extern int32_t Towers$freelist;
extern int32_t Towers$movesdone;
void Towers$Makenull(int32_t s);
int32_t Towers$Getelement();
void Towers$Push(int32_t i, int32_t s);
void Towers$Init(int32_t s, int32_t n);
int32_t Towers$Pop(int32_t s);
void Towers$Move(int32_t s1, int32_t s2);
void Towers$tower(int32_t i, int32_t j, int32_t k);
void Towers$Run();
struct Towers$element$Class$ {
    struct Towers$element$Class$* super$;
};
extern struct Towers$element$Class$ Towers$element$class$;

extern void Towers$init$(void);
extern OBX$Cmd Towers$cmd$(const char* name);
#endif
